/**
 * The Private Edition catalog snapshots — roadmap 7.10 (CR-02), shipped
 * 30.09.2026 on Sonny's decision.
 *
 * SAP publishes one moving release list per edition and, for the Private
 * Edition, release-pinned lists as well (`RELEASE_FILES` in
 * `cloudification-repo.ts`). Until now the build shipped only the Public
 * list, so every Private Edition project was read against it. This module
 * registers the four PCE files with `catalog-service.ts` and says which one a
 * target reads.
 *
 * **Server only.** `catalog-service.ts` reaches the browser through the
 * evidence engine; importing the PCE files there would add ~6 MB to a client
 * bundle. Only routes import this module, so only the server holds the data.
 *
 * Same source and same treatment as the files already shipped: generated by
 * `scripts/sync-cloudification-repo.ts` from github.com/SAP/abap-atc-cr-cv-s4hc,
 * refreshed by `.github/workflows/sync-catalog.yml`.
 */

import pceLatest from './generated/cloudification-repo.pce-latest.json';
import pce2025_1 from './generated/cloudification-repo.pce-2025-1.json';
import pce2025_0 from './generated/cloudification-repo.pce-2025-0.json';
import pce2023_3 from './generated/cloudification-repo.pce-2023-3.json';
import type { CloudificationArtifact } from './cloudification-repo';
import { getCatalogSnapshotRef, hasCatalogSnapshot, registerCatalogSnapshot } from './catalog-service';
import { EDITION_CATALOG_KEY, EDITIONS, expectedCatalogKey, type Edition } from '../assessment-profile';

for (const artifact of [pceLatest, pce2025_1, pce2025_0, pce2023_3]) {
  registerCatalogSnapshot(artifact as unknown as CloudificationArtifact);
}

/**
 * The snapshot a target reads: the pinned file for a named Private Edition
 * release SAP publishes one for, the edition's moving list otherwise.
 *
 * When that snapshot is not registered in this process the default file is
 * read — and the profile built from the returned ref names the substitution
 * (`snapshot-substituted`), so it is never silent.
 */
export function catalogSnapshotKeyFor(edition: string, release: string): string {
  const expected = expectedCatalogKey(edition, release);
  if (expected && hasCatalogSnapshot(expected)) return expected;
  const fallback = (EDITIONS as readonly string[]).includes(edition) ? EDITION_CATALOG_KEY[edition as Edition] : null;
  if (fallback && hasCatalogSnapshot(fallback)) return fallback;
  return getCatalogSnapshotRef().registryKey;
}

/** The snapshot a project's current declaration reads — for the live side of the profile comparison. */
export function catalogSnapshotRefForProject(project: unknown): { registryKey: string; sourceSha256: string } {
  const p = (project && typeof project === 'object' ? project : {}) as Record<string, unknown>;
  const edition = typeof p.s4Deployment === 'string' ? p.s4Deployment : '';
  const target = p.assessmentTarget as { release?: unknown } | undefined;
  const release = typeof target?.release === 'string' ? target.release : '';
  return catalogSnapshotRefFor(edition, release);
}

/** `catalogSnapshotKeyFor` as the ref a run records (key and digest). */
export function catalogSnapshotRefFor(edition: string, release: string): { registryKey: string; sourceSha256: string } {
  return getCatalogSnapshotRef(catalogSnapshotKeyFor(edition, release));
}
