/**
 * Layered SAP API catalog service.
 *
 * Layer 1 (wins):  SAP_API_CATALOG — hand-curated, carries field-level knowledge
 *                  and transformation semantics. confidence: 'curated'.
 * Layer 2:         SAP Cloudification Repository (generated artifact) — broad,
 *                  official, per-release, object-level successors.
 *                  confidence: 'sap-official'.
 *
 * Exposes:
 *   MERGED_TABLE_MAP        — drop-in replacement for STANDARD_TABLE_MAP in
 *                             evidence-model.ts (same {view,type} shape, plus
 *                             confidence/state extras).
 *   NO_PATH_OBJECTS         — objects the repo lists WITHOUT successors and not
 *                             released → honest 'no released-API path' signal.
 *   resolveApi()            — full lookup incl. all successors + concept notes.
 *   getMergedCatalogVersion() — traceability string for Audit Pack / model card.
 */

import { SAP_API_CATALOG, SAP_API_CATALOG_VERSION, type SapApiEntry, type SapApiObjectType } from './sap-api-catalog';
import type { CloudificationArtifact, NormalizedEntry } from './cloudification-repo';

// Generated by scripts/sync-cloudification-repo.ts. resolveJsonModule must be on
// (tsconfig "resolveJsonModule": true — already required by other imports; verify).
// The stub shipped with this patch keeps the build green until the first sync runs.
import crLatest from './generated/cloudification-repo.latest.json';

const CR: CloudificationArtifact = crLatest as unknown as CloudificationArtifact;

export type CatalogConfidence = 'curated' | 'sap-official';

export interface MergedApiEntry extends SapApiEntry {
  confidence: CatalogConfidence;
  /** verbatim repo state when the entry (also) exists in the repo layer */
  releaseState?: string;
  /** all successors from the repo (curated layer only knows the primary) */
  successors?: { name: string; tadir: string }[];
  conceptNote?: string;
}

function tadirToType(tadir: string): SapApiObjectType {
  switch (tadir) {
    case 'DDLS':
    case 'VIEW': return 'CDS View';
    case 'SRVD':
    case 'SRVB': return 'OData API';
    case 'FUNC': return 'BAPI';
    default: return 'Unknown';
  }
}

function buildMerged(): { map: Record<string, MergedApiEntry>; noPath: Set<string> } {
  const map: Record<string, MergedApiEntry> = {};
  const noPath = new Set<string>();

  // Layer 2 first (so layer 1 overwrites).
  for (const [name, e] of Object.entries<NormalizedEntry>(CR.entries ?? {})) {
    const released = e.state?.toLowerCase() === 'released';
    const primary = e.successors?.[0];

    if (primary) {
      map[name] = {
        view: primary.name,
        type: tadirToType(primary.tadir),
        confidence: 'sap-official',
        releaseState: e.state,
        successors: e.successors,
        conceptNote: e.conceptNote,
      };
    } else if (e.conceptNote) {
      // Successor is a concept, not an object — do NOT fabricate a mapping.
      noPath.add(name);
    } else if (!released) {
      // Listed, not released, no successor → honest no-path signal.
      noPath.add(name);
    }
    // released && no successor → object itself is a released API; nothing to map.
  }

  // Layer 1: curated entries always win (field-level knowledge).
  for (const [name, e] of Object.entries(SAP_API_CATALOG)) {
    const repo = CR.entries?.[name];
    map[name] = {
      ...e,
      confidence: 'curated',
      releaseState: repo?.state,
      successors: repo?.successors,
    };
    noPath.delete(name); // a curated mapping overrides a repo no-path verdict
  }

  return { map, noPath };
}

const built = buildMerged();

/** Drop-in for evidence-model's STANDARD_TABLE_MAP (superset of SapApiEntry). */
export const MERGED_TABLE_MAP: Record<string, MergedApiEntry> = built.map;

/** Objects with an honest 'no released-API path' verdict from the repo layer. */
export const NO_PATH_OBJECTS: ReadonlySet<string> = built.noPath;

export function resolveApi(objectName: string): MergedApiEntry | undefined {
  return MERGED_TABLE_MAP[(objectName || '').toUpperCase()];
}

export function hasNoReleasedApiPath(objectName: string): boolean {
  return NO_PATH_OBJECTS.has((objectName || '').toUpperCase());
}

export const MERGED_CATALOG_SIZE = Object.keys(MERGED_TABLE_MAP).length;

/** Lightweight stats for landing page badge — avoids importing the full artifact. */
export function getCatalogStats(): { classifiedObjects: number; mappedWithSuccessor: number; syncDate: string } {
  return {
    classifiedObjects: CR.meta?.entryCount || 0,
    mappedWithSuccessor: MERGED_CATALOG_SIZE,
    syncDate: (CR.meta?.fetchedAt || '').slice(0, 10),
  };
}

/**
 * Traceability string for Audit Pack / model card, e.g.
 * "2024.FPS02 + CR:latest@e3b0c442 (4812 entries, fetched 2026-07-01)"
 */
export function getMergedCatalogVersion(): string {
  const m = CR.meta;
  if (!m?.sourceSha256) return SAP_API_CATALOG_VERSION; // stub / pre-first-sync
  const shortSha = m.sourceSha256.slice(0, 8);
  const day = (m.fetchedAt || '').slice(0, 10);
  return `${SAP_API_CATALOG_VERSION} + CR:${m.release}@${shortSha} (${m.entryCount} entries, fetched ${day})`;
}

