/**
 * Layered SAP API catalog service.
 *
 * Layer 1 (wins):  SAP_API_CATALOG — hand-curated, carries field-level knowledge
 *                  and transformation semantics. confidence: 'curated'.
 * Layer 2:         SAP Cloudification Repository (generated artifact) — broad,
 *                  official, per-release, object-level successors.
 *                  confidence: 'sap-official'.
 *
 * Exposes:
 *   MERGED_TABLE_MAP        — drop-in replacement for STANDARD_TABLE_MAP in
 *                             evidence-model.ts (same {view,type} shape, plus
 *                             confidence/state extras).
 *   NO_PATH_OBJECTS         — objects the repo lists WITHOUT successors and not
 *                             released → honest 'no released-API path' signal.
 *   resolveApi()            — full lookup incl. all successors + concept notes.
 *   getMergedCatalogVersion() — traceability string for Audit Pack / model card.
 */

import { SAP_API_CATALOG, SAP_API_CATALOG_VERSION, type SapApiEntry, type SapApiObjectType } from './sap-api-catalog';
import type { CloudificationArtifact, NormalizedEntry } from './cloudification-repo';
import {
  gradeFromSapStates,
  gradeFromSapStatesForUse,
  isCustomerObject,
  isNamespacedObject,
  type GradedObject,
  type ObjectUse,
  type SapObjectStates,
  type CloudReadinessGrade,
} from './abcd-classification';
import { enumerateLevelRule, fingerprintLevelRule } from './level-rule-version';

// Generated by scripts/sync-cloudification-repo.ts. resolveJsonModule must be on
// (tsconfig "resolveJsonModule": true — already required by other imports; verify).
// The stub shipped with this patch keeps the build green until the first sync runs.
import crLatest from './generated/cloudification-repo.latest.json';
// formatVersion 2 companion file: classicAPI / noAPI. Near-disjoint from the
// release file (190 of 8,587 keys overlap at the 2026-09-15 sync), so it is additional coverage.
import crClassifications from './generated/cloudification-repo.classifications-sap.json';

const CR: CloudificationArtifact = crLatest as unknown as CloudificationArtifact;
const CR_CLASS: CloudificationArtifact = crClassifications as unknown as CloudificationArtifact;

export type CatalogConfidence = 'curated' | 'sap-official';

export interface MergedApiEntry extends SapApiEntry {
  confidence: CatalogConfidence;
  /** verbatim repo state when the entry (also) exists in the repo layer */
  releaseState?: string;
  /** all successors from the repo (curated layer only knows the primary) */
  successors?: { name: string; tadir: string }[];
  conceptNote?: string;
}

function tadirToType(tadir: string): SapApiObjectType {
  switch (tadir) {
    case 'DDLS':
    case 'VIEW': return 'CDS View';
    case 'SRVD':
    case 'SRVB': return 'OData API';
    case 'FUNC': return 'BAPI';
    default: return 'Unknown';
  }
}

function buildMerged(): { map: Record<string, MergedApiEntry>; noPath: Set<string> } {
  const map: Record<string, MergedApiEntry> = {};
  const noPath = new Set<string>();

  // Layer 2 first (so layer 1 overwrites).
  for (const [name, e] of Object.entries<NormalizedEntry>(CR.entries ?? {})) {
    const released = e.state?.toLowerCase() === 'released';
    const primary = e.successors?.[0];

    if (primary) {
      map[name] = {
        view: primary.name,
        type: tadirToType(primary.tadir),
        confidence: 'sap-official',
        releaseState: e.state,
        successors: e.successors,
        conceptNote: e.conceptNote,
      };
    } else if (e.conceptNote) {
      // Successor is a concept, not an object — do NOT fabricate a mapping.
      noPath.add(name);
    } else if (!released) {
      // Listed, not released, no successor → honest no-path signal.
      noPath.add(name);
    }
    // released && no successor → object itself is a released API; nothing to map.
  }

  // Layer 1: curated entries always win (field-level knowledge).
  for (const [name, e] of Object.entries(SAP_API_CATALOG)) {
    const repo = CR.entries?.[name];
    map[name] = {
      ...e,
      confidence: 'curated',
      releaseState: repo?.state,
      successors: repo?.successors,
    };
    noPath.delete(name); // a curated mapping overrides a repo no-path verdict
  }

  return { map, noPath };
}

const built = buildMerged();

/** Drop-in for evidence-model's STANDARD_TABLE_MAP (superset of SapApiEntry). */
export const MERGED_TABLE_MAP: Record<string, MergedApiEntry> = built.map;

/** Objects with an honest 'no released-API path' verdict from the repo layer. */
export const NO_PATH_OBJECTS: ReadonlySet<string> = built.noPath;

export function resolveApi(objectName: string): MergedApiEntry | undefined {
  return MERGED_TABLE_MAP[(objectName || '').toUpperCase()];
}

export function hasNoReleasedApiPath(objectName: string): boolean {
  return NO_PATH_OBJECTS.has((objectName || '').toUpperCase());
}

export const MERGED_CATALOG_SIZE = Object.keys(MERGED_TABLE_MAP).length;

/**
 * Lightweight stats for the public surfaces.
 *
 * `classifiedObjects` counts the UNION of both repository artifacts, because
 * that is the set of objects we can state a clean core level for. Counting only
 * the release file would understate coverage by the 8,587 objects the
 * classification file adds — and would contradict the A–D census on
 * /sap-clean-core-object-classification, which is the kind of mismatch that gets
 * a figure mis-cited.
 */
export function getCatalogStats(): {
  classifiedObjects: number;
  mappedWithSuccessor: number;
  syncDate: string;
} {
  const keys = new Set<string>([
    ...Object.keys(CR.entries ?? {}),
    ...Object.keys(CR_CLASS.entries ?? {}),
  ]);
  // Newest of the two syncs — the figure is only as current as its stalest half,
  // but the label reads "as of", so the later date is the honest one to show.
  const dates = [CR.meta?.fetchedAt, CR_CLASS.meta?.fetchedAt].filter(Boolean) as string[];
  const syncDate = dates.length ? dates.sort().slice(-1)[0].slice(0, 10) : '';

  return {
    classifiedObjects: keys.size,
    mappedWithSuccessor: MERGED_CATALOG_SIZE,
    syncDate,
  };
}

/**
 * Traceability string for Audit Pack / model card, e.g.
 * "2024.FPS02 + CR:latest@e3b0c442 (4812 entries, fetched 2026-07-01)"
 */
export function getMergedCatalogVersion(): string {
  const m = CR.meta;
  if (!m?.sourceSha256) return SAP_API_CATALOG_VERSION; // stub / pre-first-sync
  const shortSha = m.sourceSha256.slice(0, 8);
  const day = (m.fetchedAt || '').slice(0, 10);
  return `${SAP_API_CATALOG_VERSION} + CR:${m.release}@${shortSha} (${m.entryCount} entries, fetched ${day})`;
}


/* ---------- clean core level (A–D) lookup ---------- */

/**
 * SAP's published state for an object, from both repository files.
 *
 * Server-side only: it reads the full generated artifacts (~5 MB combined), so
 * never import this into a client component. Client surfaces get the resolved
 * grade, not the map.
 */
export function getSapObjectStates(objectName: string): SapObjectStates {
  const key = (objectName || '').toUpperCase().trim();
  const release = CR.entries?.[key];
  const classification = CR_CLASS.entries?.[key];

  // "isSapObject" drives the residual level C verdict, so it must mean "we know
  // this is SAP's". A Z/Y object is not, and a /NS/ object that appears in
  // neither artifact is unknown provenance — claiming either is SAP-internal
  // would be a grade we cannot support.
  const listed = Boolean(release || classification);
  return {
    releaseState: release?.state,
    classificationState: classification?.state,
    hasSuccessor: Boolean(release?.successors?.length || classification?.successors?.length),
    isSapObject: !isCustomerObject(key) && (listed || !isNamespacedObject(key)),
    isCustomerObject: isCustomerObject(key),
  };
}

/**
 * Clean core level for a single object, derived from SAP data where it exists.
 *
 * Returns provenance alongside the grade so the UI can separate a looked-up
 * grade from an estimated one — the distinction the public pages promise.
 *
 * This is the answer for the *name*. Where the code's use of the object is
 * known, `gradeSapObjectUse` is the answer the analysis shows.
 */
export function gradeSapObject(objectName: string): GradedObject {
  return gradeFromSapStates(getSapObjectStates(objectName));
}

/**
 * Clean core level for one use of an object — the grade the analysis panel
 * shows next to a table the code reads or writes (`/api/abcd-classify`), and
 * the grade the reference corpus compares, so the two cannot drift apart.
 */
export function gradeSapObjectUse(objectName: string, use: ObjectUse | null): GradedObject {
  return gradeFromSapStatesForUse(getSapObjectStates(objectName), use);
}

/** SAP object types the repository files list that code reads and writes as data. */
const DATA_OBJECT_TYPES = new Set(['TABL', 'VIEW', 'DDLS']);

/**
 * Both answers for a data object whose level depends on the access, or `null`.
 *
 * The catalog page has no code to look at, so for KNA1 it cannot know whether
 * the reader reads or writes. Where that decides the level it shows both rather
 * than the stricter one alone; everywhere else there is one answer and this
 * returns nothing.
 */
export function gradeSapObjectUses(objectName: string): { read: GradedObject; write: GradedObject } | null {
  const key = (objectName || '').toUpperCase().trim();
  const tadir = CR.entries?.[key]?.tadir ?? CR_CLASS.entries?.[key]?.tadir;
  if (!tadir || !DATA_OBJECT_TYPES.has(tadir)) return null;
  const read = gradeSapObjectUse(key, 'read');
  const write = gradeSapObjectUse(key, 'write');
  return read.grade === write.grade ? null : { read, write };
}

export interface LevelDerivationCensus {
  totalObjects: number;
  releaseFileOnly: number;
  classificationFileOnly: number;
  inBoth: number;
  /** Every state pairing that occurs, with the level it produces. */
  combinations: {
    releaseState: string | null;
    classificationState: string | null;
    grade: CloudReadinessGrade;
    objects: number;
    /**
     * How many of them SAP names a replacement for.
     *
     * Counted rather than inferred. The rule page needs it to say "21 of the 22
     * carry a successor", and writing that as `total - 1` would be arithmetic
     * standing in for a measurement — true today, and silently wrong the first
     * time a catalog sync changes the shape.
     */
    withSuccessor: number;
  }[];
}

/**
 * The derivation, counted rather than described.
 *
 * `/method/levels` publishes the precedence rule, and a rule page whose numbers
 * are typed by hand is a rule page that goes stale silently. Every figure it
 * prints comes from here, computed over the two artifacts at build time — so a
 * catalog sync that changes the shape of the data changes the page with it.
 *
 * The pairings matter more than the totals: the twenty-two objects where the two
 * files disagree are the whole reason the page exists, and they are a row here
 * rather than a sentence someone has to keep true.
 */
export function getLevelDerivationCensus(): LevelDerivationCensus {
  const releaseKeys = Object.keys(CR.entries ?? {});
  const classificationKeys = Object.keys(CR_CLASS.entries ?? {});
  const all = new Set<string>([...releaseKeys, ...classificationKeys]);

  let inBoth = 0;
  const buckets = new Map<string, LevelDerivationCensus['combinations'][number]>();

  for (const key of all) {
    const release = CR.entries?.[key];
    const classification = CR_CLASS.entries?.[key];
    if (release && classification) inBoth += 1;

    const releaseState = release?.state ?? null;
    const classificationState = classification?.state ?? null;
    const grade = gradeSapObject(key).grade;
    const hasSuccessor = Boolean(release?.successors?.length || classification?.successors?.length);

    // A deprecated object grades C or D depending on whether SAP named a
    // successor, so the successor flag is part of the pairing's identity.
    const id = `${releaseState}|${classificationState}|${grade}`;
    const existing = buckets.get(id);
    if (existing) {
      existing.objects += 1;
      if (hasSuccessor) existing.withSuccessor += 1;
    } else {
      buckets.set(id, {
        releaseState,
        classificationState,
        grade,
        objects: 1,
        withSuccessor: hasSuccessor ? 1 : 0,
      });
    }
  }

  return {
    totalObjects: all.size,
    // From the intersection, not from the total: `all.size - otherFile.length`
    // gives the same answer only while every object is in at least one file,
    // which is true today and is not a property either artifact guarantees.
    releaseFileOnly: releaseKeys.length - inBoth,
    classificationFileOnly: classificationKeys.length - inBoth,
    inBoth,
    combinations: [...buckets.values()].sort((a, b) => b.objects - a.objects),
  };
}

/** One of the two synced SAP artifacts the level is derived from. */
export interface LevelRuleArtifact {
  /** file name as SAP publishes it, taken from the URL that was fetched */
  file: string;
  /** the question this file answers — the reason there are two of them */
  question: string;
  /** registry key of the sync (e.g. 'latest', 'classifications-sap') */
  release: string;
  /** first eight hex characters of the SHA-256 of the raw file SAP served */
  sha256: string;
  /** date of the sync, YYYY-MM-DD */
  fetchedAt: string;
  entries: number;
}

export interface LevelRuleVersion {
  /** twelve hex characters over the rule's full decision table */
  fingerprint: string;
  /** how many distinct inputs that table covers — the fingerprint's reach */
  decisions: number;
  artifacts: LevelRuleArtifact[];
  /** the one line a reader can quote back at us */
  version: string;
}

let levelRuleVersionCache: LevelRuleVersion | null = null;

/**
 * Which version of the A–D rule produced the level you are looking at.
 *
 * Two halves, both measured:
 *
 *   the rule   — every input `gradeFromSapStatesForUse` can tell apart (the two
 *                states, the owner, and how the code uses the object),
 *                enumerated and hashed (see `level-rule-version.ts`). The states SAP actually
 *                ships are read out of the artifacts and folded into the domain,
 *                so a state nobody anticipated moves the fingerprint too.
 *   the data   — the release and the SHA-256 SAP served, per file, with the date
 *                of the sync.
 *
 * Nothing here is typed by hand, which is the whole point: `/method/levels`
 * prints this string, and a version string a page author maintains is correct
 * exactly once.
 */
export function getLevelRuleVersion(): LevelRuleVersion {
  if (levelRuleVersionCache) return levelRuleVersionCache;

  const statesOf = (a: CloudificationArtifact) =>
    [...new Set(Object.values(a.entries ?? {}).map((e) => e.state).filter(Boolean))];

  const decisions = enumerateLevelRule({
    releaseStates: statesOf(CR),
    classificationStates: statesOf(CR_CLASS),
  });
  const fingerprint = fingerprintLevelRule(decisions);

  const artifact = (a: CloudificationArtifact, question: string): LevelRuleArtifact => ({
    file: (a.meta?.source || '').split('/').pop() || 'unknown',
    question,
    release: a.meta?.release || 'unknown',
    sha256: (a.meta?.sourceSha256 || '').slice(0, 8),
    fetchedAt: (a.meta?.fetchedAt || '').slice(0, 10),
    entries: a.meta?.entryCount ?? Object.keys(a.entries ?? {}).length,
  });

  const artifacts = [
    artifact(CR, 'Can ABAP Cloud use this object?'),
    artifact(CR_CLASS, 'What does classic ABAP using it count as?'),
  ];

  levelRuleVersionCache = {
    fingerprint,
    decisions: decisions.length,
    artifacts,
    version: `levels ${fingerprint} · ${artifacts.map((a) => `${a.release}@${a.sha256}`).join(' · ')}`,
  };
  return levelRuleVersionCache;
}

/**
 * A–D distribution across everything SAP has published, for the public
 * reference page. This is a census of SAP's own data, not of any customer's
 * code — labelled as such wherever it is shown.
 */
export function getPublishedGradeDistribution(): {
  distribution: Record<CloudReadinessGrade, number>;
  totalObjects: number;
  releaseSource: { release: string; sha256: string; fetchedAt: string };
  classificationSource: { release: string; sha256: string; fetchedAt: string };
} {
  const distribution: Record<CloudReadinessGrade, number> = { A: 0, B: 0, C: 0, D: 0, Unknown: 0 };
  const seen = new Set<string>();

  const tally = (key: string) => {
    if (seen.has(key)) return;
    seen.add(key);
    distribution[gradeSapObject(key).grade] += 1;
  };

  for (const key of Object.keys(CR.entries ?? {})) tally(key);
  for (const key of Object.keys(CR_CLASS.entries ?? {})) tally(key);

  const src = (a: CloudificationArtifact) => ({
    release: a.meta?.release || 'unknown',
    sha256: (a.meta?.sourceSha256 || '').slice(0, 8),
    fetchedAt: (a.meta?.fetchedAt || '').slice(0, 10),
  });

  return {
    distribution,
    totalObjects: seen.size,
    releaseSource: src(CR),
    classificationSource: src(CR_CLASS),
  };
}
