/**
 * English business words for ABAP identifiers — the counterpart of
 * `business-glossary.ts` for the English product UI.
 *
 * `plain-language.ts` builds process-map labels from these tables without any
 * language model. A translation is an interpretation, so every one of them is
 * written down here, in one place, where it can be checked or struck out. An
 * identifier that is not listed is never guessed at: it is shown as a
 * humanised version of the name the source writes.
 *
 * Sources: the short descriptions of the SAP standard data elements and tables
 * (ABAP Dictionary, SAP Help Portal), shortened to the business word. Every key
 * of `FIELD_TERMS` and `TABLE_TERMS` in `business-glossary.ts` has an entry here
 * (held by `tests/plain-language.spec.ts`).
 *
 * No imports: pure data, readable by a client component.
 */

export interface PlainTerm {
  /** How a label names one of it. */
  singular: string;
  /** How a label names several of it. */
  plural: string;
  /** A shorter singular, used only when the full wording does not fit a label. */
  short?: string;
}

const t = (singular: string, plural?: string): PlainTerm => ({ singular, plural: plural ?? `${singular}s` });
/** A word that does not inflect (data, stock, status …). */
const same = (word: string): PlainTerm => ({ singular: word, plural: word });

/**
 * Database fields and variable stems → business word. Keys are lower case and
 * without the usual ABAP prefixes (`lv_`, `gs_`, `p_` …).
 */
export const FIELD_TERMS_EN: Readonly<Record<string, PlainTerm>> = Object.freeze({
  // --- keys of FIELD_TERMS in business-glossary.ts ------------------------
  kunnr: t('Customer number'),
  customer: t('Customer'),
  name1: t('Name'),
  customername: t('Customer name'),
  name: t('Name'),
  land1: t('Country', 'Countries'),
  land: t('Country', 'Countries'),
  country: t('Country', 'Countries'),
  bukrs: t('Company code'),
  akont: t('Reconciliation account'),
  vkorg: t('Sales organization'),
  vtweg: t('Distribution channel'),
  spart: t('Division'),
  mandt: t('Client'),
  bname: t('User name'),
  bcode: t('Password hash', 'Password hashes'),
  uflag: same('Lock status'),
  vbeln: t('Document number'),
  auart: t('Order type'),
  netwr: t('Net value'),
  lifsk: t('Delivery block'),
  // Roadmap 3.0.7: the schedule-line date a batch input to ME22 changes.
  eindt: t('Delivery date'),
  eeind: t('Delivery date'),
  amount: t('Amount'),
  amt: t('Amount'),
  betrag: t('Amount'),
  route: t('Route'),
  status: same('Status'),
  count: t('Count'),
  sum: t('Sum'),
  min: t('Minimum', 'Minimums'),
  value: t('Value'),
  text: t('Text'),
  key: t('Key'),
  keys: t('Key'),
  id: t('ID'),
  case_id: t('Case ID'),
  case: t('Case'),
  review: t('Review flag'),
  title: t('Title'),
  tab: t('Table'),
  func: t('Function module'),
  function: t('Function module'),
  prog: t('Program'),
  form: t('Subroutine'),
  dest: t('Destination'),
  field: t('Field'),
  rows: t('Row'),
  row: t('Row'),
  result: t('Result'),
  total: t('Total'),
  rule: t('Rule'),
  user: t('User'),
  type: t('Type'),
  where: t('Condition'),
  matnr: t('Material'),
  werks: t('Plant'),
  lgort: t('Storage location'),
  charg: t('Batch', 'Batches'),
  menge: t('Quantity', 'Quantities'),
  meins: t('Unit of measure', 'Units of measure'),
  waers: t('Currency', 'Currencies'),
  waerk: t('Document currency', 'Document currencies'),
  posnr: t('Item number'),
  ebeln: t('Purchase order number'),
  ebelp: t('Purchase order item'),
  banfn: { ...t('Purchase requisition number'), short: 'Requisition number' },
  lifnr: t('Supplier number'),
  belnr: t('Document number'),
  gjahr: t('Fiscal year'),
  budat: t('Posting date'),
  bldat: t('Document date'),
  hkont: t('G/L account'),
  saknr: t('G/L account'),
  kostl: t('Cost center'),
  prctr: t('Profit center'),
  kokrs: t('Controlling area'),
  aufnr: t('Order number'),
  ekorg: t('Purchasing organization'),
  ekgrp: t('Purchasing group'),
  bwart: t('Movement type'),
  mblnr: t('Material document number'),
  pernr: t('Personnel number'),
  equnr: t('Equipment number'),
  qmnum: t('Notification number'),
  vornr: t('Operation number'),
  arbpl: t('Work center'),
  abgru: t('Rejection reason'),
  faksk: t('Billing block'),
  aufsd: t('Order block'),
  loevm: t('Deletion flag'),
  kwmeng: t('Order quantity', 'Order quantities'),
  lfimg: t('Delivery quantity', 'Delivery quantities'),
  vstel: t('Shipping point'),
  spras: t('Language'),
  ernam: t('Created by', 'Created by'),
  erdat: t('Creation date'),
  aedat: t('Change date'),
  dmbtr: { ...t('Amount in local currency', 'Amounts in local currency'), short: 'Local amount' },
  wrbtr: { ...t('Amount in document currency', 'Amounts in document currency'), short: 'Document amount' },
  shkzg: t('Debit/credit indicator'),

  // --- further SAP standard fields seen in customer code -------------------
  frgkz: t('Release indicator'),
  frggr: t('Release group'),
  frgst: t('Release strategy', 'Release strategies'),
  dispo: t('MRP controller'),
  bednr: { ...t('Requirement tracking number'), short: 'Tracking number' },
  bnfpo: t('Requisition item'),
  flief: t('Fixed supplier'),
  loekz: t('Deletion indicator'),
  statu: same('Processing status'),
  preis: t('Price'),
  netpr: t('Net price'),
  peinh: t('Price unit'),
  esart: t('Document type'),
  bsart: t('Document type'),
  sperr: t('Central block'),
  ktokd: t('Account group'),
  regio: t('Region'),
  zterm: same('Payment terms'),
  pstyv: t('Item category', 'Item categories'),
  mtart: t('Material type'),
  matkl: t('Material group'),
  labst: same('Unrestricted stock'),
  insme: same('Stock in quality inspection'),
  bmeng: t('Confirmed quantity', 'Confirmed quantities'),
  cmgst: same('Credit status'),
  bstnk: t('Customer reference'),
  vbtyp: t('Document category', 'Document categories'),
  fkart: t('Billing type'),
  fkdat: t('Billing date'),
  partner: t('Business partner'),
  smtp_addr: t('E-mail address', 'E-mail addresses'),
  uname: t('User'),
  datum: t('Date'),
  uzeit: t('Time'),
  infnr: t('Info record number'),
  mwskz: t('Tax code'),
  vkbur: t('Sales office'),
  vkgrp: t('Sales group'),
  kdgrp: t('Customer group'),
  inco1: t('Incoterm'),
  lfart: t('Delivery type'),
  wadat: t('Goods issue date'),
  lfdat: t('Delivery date'),
  edatu: t('Schedule line date'),
  prsdt: t('Pricing date'),
  zfbdt: t('Baseline date'),
  augbl: t('Clearing document'),
  augdt: t('Clearing date'),
  stras: t('Street'),
  ort01: t('City', 'Cities'),
  pstlz: t('Postal code'),
  telf1: t('Telephone number'),
  // --- the user command of a screen or an ALV list -------------------------
  ucomm: t('User command'),
  okcode: t('User command'),
  ok_code: t('User command'),
  fcode: t('Function code'),
});

/** Database tables and read models → the business object behind them. */
export const TABLE_TERMS_EN: Readonly<Record<string, PlainTerm>> = Object.freeze({
  // --- keys of TABLE_TERMS in business-glossary.ts ------------------------
  kna1: t('Customer'),
  knb1: same('Customer company code data'),
  knvv: same('Customer sales data'),
  i_customer: t('Customer'),
  usr02: t('User'),
  vbak: t('Sales order'),
  zi_order: t('Order'),
  zcc_decision: t('Case'),
  zcc_case: t('Case'),
  vbap: t('Sales order item'),
  vbep: t('Schedule line'),
  vbpa: t('Document partner'),
  vbfa: t('Document flow record'),
  likp: t('Delivery', 'Deliveries'),
  lips: t('Delivery item'),
  vbrk: t('Billing document'),
  vbrp: t('Billing document item'),
  konv: t('Condition record'),
  knvp: t('Customer partner'),
  mara: t('Material'),
  makt: t('Material description'),
  marc: same('Material plant data'),
  mard: same('Storage location stock'),
  mbew: t('Material valuation'),
  mkpf: t('Material document'),
  mseg: t('Material document item'),
  mch1: t('Batch', 'Batches'),
  mcha: t('Batch', 'Batches'),
  ekko: t('Purchase order'),
  ekpo: t('Purchase order item'),
  eket: t('Purchase order schedule line'),
  eban: t('Purchase requisition'),
  lfa1: t('Supplier'),
  lfb1: same('Supplier company code data'),
  t001w: t('Plant'),
  t001l: t('Storage location'),
  bkpf: t('Accounting document'),
  bseg: t('Accounting document item'),
  acdoca: t('Journal entry item'),
  bsid: t('Open customer item'),
  bsad: t('Cleared customer item'),
  bsik: t('Open supplier item'),
  bsak: t('Cleared supplier item'),
  bsis: t('Open G/L item'),
  bsas: t('Cleared G/L item'),
  ska1: t('G/L account'),
  skb1: t('G/L account'),
  t001: t('Company code'),
  tcurr: t('Exchange rate'),
  csks: t('Cost center'),
  cska: t('Cost element'),
  cepc: t('Profit center'),
  aufk: t('Order master record'),
  afko: t('Production order'),
  afpo: t('Production order item'),
  afvc: t('Operation'),
  resb: t('Reservation item'),
  stko: t('Bill of material', 'Bills of material'),
  stpo: t('Bill of material item'),
  plko: t('Routing'),
  crhd: t('Work center'),
  equi: t('Equipment', 'Equipment'),
  iflot: t('Functional location'),
  qmel: t('Notification'),
  afih: t('Maintenance order'),
  imptt: t('Measuring point'),
  imrg: t('Measurement document'),
  qals: t('Inspection lot'),
  vttk: t('Shipment'),
  vttp: t('Shipment item'),
  ltak: t('Transfer order'),
  ltap: t('Transfer order item'),
  lqua: t('Quant'),
  lagp: t('Storage bin'),
  pa0000: t('Personnel action'),
  pa0001: same('Organizational assignment'),
  pa0002: same('Personal data'),
  pa0008: same('Basic pay'),
  but000: t('Business partner'),
  adrc: t('Address', 'Addresses'),
  adr6: t('E-mail address', 'E-mail addresses'),
  tvarvc: t('Variable entry', 'Variable entries'),
  t100: t('Message text'),
  jest: same('Object status'),
  nast: t('Output message'),
  edidc: t('IDoc control record'),
  edid4: t('IDoc data record'),
  tbtco: t('Background job'),

  // --- further SAP standard tables seen in customer code -------------------
  lfm1: same('Supplier purchasing data'),
  eina: t('Purchasing info record'),
  eine: same('Info record purchasing data'),
  t16fs: t('Release strategy', 'Release strategies'),
  pa0105: same('Communication data'),
  tvko: t('Sales organization'),
  but020: t('Business partner address', 'Business partner addresses'),
  knvk: t('Customer contact'),
  vbkd: same('Sales document business data'),
  vbuk: same('Sales document status'),
  vbup: same('Sales item status'),
  t024: t('Purchasing group'),
  t024e: t('Purchasing organization'),
  csks_t: t('Cost center text'),
});

/**
 * Abbreviations a variable stem often carries. Applied word by word to an
 * identifier stem when it has no entry of its own above.
 */
export const STEM_ABBREVIATIONS: Readonly<Record<string, string>> = Object.freeze({
  lim: 'limit',
  qty: 'quantity',
  amt: 'amount',
  pct: 'percent',
  dev: 'deviation',
  max: 'maximum',
  min: 'minimum',
  cnt: 'count',
  num: 'number',
  nr: 'number',
  no: 'number',
  dat: 'date',
  upd: 'update',
  del: 'delete',
  err: 'error',
  msg: 'message',
  ref: 'reference',
  curr: 'currency',
  stat: 'status',
  desc: 'description',
  mail: 'mail',
  down: 'download',
  file: 'file',
  test: 'test run',
  bdc: 'batch input',
  alv: 'ALV list',
  rfc: 'remote call',
  bp: 'business partner',
  po: 'purchase order',
  pr: 'purchase requisition',
  cust: 'customer',
  mat: 'material',
  vend: 'vendor',
  doc: 'document',
  docs: 'documents',
  addr: 'address',
  tot: 'total',
  avg: 'average',
  prio: 'priority',
  info: 'info',
  log: 'log entry',
  return: 'return message',
  dept: 'department',
  fieldcat: 'field catalog',
  fcat: 'field catalog',
});

/**
 * Abbreviations inside routine names. Smaller than the stem table on purpose:
 * `NO_ACTION` is not "number action" and `RUN_TEST` is not "run test run".
 */
export const ROUTINE_ABBREVIATIONS: Readonly<Record<string, string>> = Object.freeze({
  bp: 'business partner',
  po: 'purchase order',
  alv: 'ALV list',
  bdc: 'batch input',
  rfc: 'remote',
  qty: 'quantity',
  amt: 'amount',
  pct: 'percent',
  msg: 'message',
  err: 'error',
  curr: 'currency',
  desc: 'description',
  ref: 'reference',
  dept: 'department',
  fieldcat: 'field catalog',
  fcat: 'field catalog',
});

/** Words written in capitals wherever they appear. */
export const ACRONYMS: ReadonlySet<string> = new Set([
  'abap', 'alv', 'api', 'bapi', 'csv', 'eur', 'usd', 'guid', 'id', 'idoc', 'json', 'mrp', 'ok', 'pdf',
  'sap', 'sd', 'mm', 'fi', 'hr', 'pp', 'pm', 'qm', 'wm', 'url', 'xml', 'iban', 'vat', 'uuid',
]);

/** Function modules a business reader knows by what they do. */
export const FUNCTION_TERMS_EN: Readonly<Record<string, string>> = Object.freeze({
  BAPI_PO_CREATE1: 'Create purchase order',
  BAPI_PO_CHANGE: 'Change purchase order',
  BAPI_PR_CREATE: 'Create purchase requisition',
  BAPI_TRANSACTION_COMMIT: 'Commit changes',
  BAPI_TRANSACTION_ROLLBACK: 'Roll back changes',
  BAPI_SALESORDER_CREATEFROMDAT2: 'Create sales order',
  BAPI_SALESORDER_CHANGE: 'Change sales order',
  BAPI_GOODSMVT_CREATE: 'Post goods movement',
  BAPI_ACC_DOCUMENT_POST: 'Post accounting document',
  BAPI_MATERIAL_SAVEDATA: 'Save material',
  BAPI_CUSTOMER_GETDETAIL2: 'Read customer',
  BAPI_BUPA_CENTRAL_GETDETAIL: 'Read business partner',
  REUSE_ALV_GRID_DISPLAY: 'Show result list',
  REUSE_ALV_LIST_DISPLAY: 'Show result list',
  GUI_DOWNLOAD: 'Download file',
  GUI_UPLOAD: 'Upload file',
  SO_NEW_DOCUMENT_SEND_API1: 'Send mail',
  SO_NEW_DOCUMENT_ATT_SEND_API1: 'Send mail',
  SAP_WAPI_CREATE_EVENT: 'Start workflow',
  SWE_EVENT_CREATE: 'Start workflow',
  GUID_CREATE: 'Create ID',
  CONVERT_TO_LOCAL_CURRENCY: 'Convert currency',
  CONVERT_TO_FOREIGN_CURRENCY: 'Convert currency',
  POPUP_TO_CONFIRM: 'Ask for confirmation',
  POPUP_TO_CONFIRM_STEP: 'Ask for confirmation',
  POPUP_TO_DECIDE: 'Ask for a decision',
  POPUP_TO_INFORM: 'Show information',
  POPUP_GET_VALUES: 'Ask for values',
  REUSE_ALV_FIELDCATALOG_MERGE: 'Build field catalog',
  ENQUEUE_EMEBANE: 'Lock purchase requisition',
  DEQUEUE_EMEBANE: 'Unlock purchase requisition',
  NUMBER_GET_NEXT: 'Draw next number',
  JOB_OPEN: 'Open background job',
  JOB_CLOSE: 'Schedule background job',
  MASTER_IDOC_DISTRIBUTE: 'Send IDoc',
  READ_TEXT: 'Read text',
  SAVE_TEXT: 'Save text',
});

/** Transaction codes a business reader knows by what they do. */
export const TRANSACTION_TERMS_EN: Readonly<Record<string, string>> = Object.freeze({
  VA01: 'Create sales order',
  VA02: 'Change sales order',
  VA03: 'Display sales order',
  ME21N: 'Create purchase order',
  ME22N: 'Change purchase order',
  ME23N: 'Display purchase order',
  ME51N: 'Create purchase requisition',
  ME52N: 'Change purchase requisition',
  MM01: 'Create material',
  MM02: 'Change material',
  MM03: 'Display material',
  XD01: 'Create customer',
  XD02: 'Change customer',
  XK01: 'Create supplier',
  XK02: 'Change supplier',
  BP: 'Maintain business partner',
  FB01: 'Post document',
  VL01N: 'Create outbound delivery',
  VL02N: 'Change outbound delivery',
  VF01: 'Create billing document',
  MIGO: 'Post goods movement',
  MIRO: 'Enter supplier invoice',
});

/** Classic event blocks → what happens at that moment, for a business reader. */
export const EVENT_TERMS_EN: Readonly<Record<string, string>> = Object.freeze({
  'LOAD-OF-PROGRAM': 'Program loaded',
  INITIALIZATION: 'Program starts',
  'AT SELECTION-SCREEN OUTPUT': 'Selection screen shown',
  'AT SELECTION-SCREEN': 'Selection entered',
  'START-OF-SELECTION': 'Run starts',
  'GET': 'Record read',
  'END-OF-SELECTION': 'Selection processed',
  'TOP-OF-PAGE': 'Page header',
  'END-OF-PAGE': 'Page footer',
  'AT LINE-SELECTION': 'Line selected',
  'AT USER-COMMAND': 'User command',
});
