import type { ClassModel } from './class-model';
import {
  SUPPORT_MATRIX, howItWorksUrl, HOW_IT_WORKS_BASE,
  type ConstructType,
} from './support-matrix';
import { extractSelects, parseSelect } from './select-parser';
import { matchCdsView } from './cds-catalog';
import { quirkRulesFor } from './sql-quirk-rules';

/**
 * Phase 3 — Grounded transformation prompt.
 *
 * The resolved ClassModel is passed to the LLM as FACTS (not inferred). The model
 * only translates method bodies and emits a structured result. Every relevant
 * construct carries a deep link to the always-current how-it-works page, so the
 * transformation output (banners, findings, report) and the public documentation
 * never drift — both derive from SUPPORT_MATRIX.
 *
 * IMPORTANT (freshness contract): the how-it-works page MUST be rendered/validated
 * from SUPPORT_MATRIX (see support-matrix.drift.test.ts). Any change to a
 * construct's support level here changes the banners, the findings, the report
 * links AND the public page in lockstep.
 */

export interface BuildPromptInput {
  model: ClassModel;
  /** Original ABAP method bodies for the leaf + uploaded ancestors, keyed by file. */
  sources: { file: string; content: string }[];
  /** Constructs detected in this transformation (drives the how-it-works refs). */
  detectedConstructs: ConstructType[];
}

/** Machine-readable JSON contract the model must return (parsed downstream). */
export const OUTPUT_CONTRACT = `Return ONLY valid JSON, no markdown, with this shape:
{
  "files": [{ "path": string, "content": string }],
  "findings": [{
    "construct": string,            // one of the known ConstructType values
    "level": "fully"|"partial"|"not-supported",
    "title": string,
    "detail": string,
    "recommendation": string,
    "location": { "file": string, "line": number },
    "targetAnchor": { "file": string, "line": number }
  }]
}`;

/** A short reference block linking each relevant construct to the live docs. */
export function howItWorksReferences(constructs: ConstructType[]): string {
  const uniq = Array.from(new Set(constructs));
  const lines = uniq.map((c) => {
    const e = SUPPORT_MATRIX[c];
    return `- ${e.title} [${e.level}] → ${howItWorksUrl(c)}`;
  });
  return [
    `Support documentation (always current, rendered from the support matrix):`,
    `Base: ${HOW_IT_WORKS_BASE}`,
    ...lines,
  ].join('\n');
}

/** Inline banner placed at the top of every generated TS file. */
export function generatedFileBanner(constructs: ConstructType[]): string {
  const uniq = Array.from(new Set(constructs));
  const ref = uniq.map((c) => ` *   - ${SUPPORT_MATRIX[c].title}: ${howItWorksUrl(c)}`).join('\n');
  return [
    '/**',
    ' * Generated by Clean-Core.io. Support levels and limitations for the',
    ' * constructs below are documented (and kept current) at:',
    ref || ` *   ${HOW_IT_WORKS_BASE}`,
    ' * Review ⚠️ partial / ❌ not-supported markers inline before going live.',
    ' */',
  ].join('\n');
}

function serializeHierarchy(model: ClassModel): string {
  // Compact, deterministic representation of the resolved facts for grounding.
  const nodes = Object.values(model.nodes).map((n) => ({
    key: n.key, kind: n.kind, isStandard: n.isStandard,
    isAbstract: n.isAbstract, isFinal: n.isFinal,
    superClass: n.superClass ?? null, interfaces: n.interfaces,
    methods: n.methods.map((m) => ({
      name: m.name, visibility: m.visibility, static: m.isStatic,
      redefinition: m.isRedefinition, abstract: m.isAbstract,
      origin: m.origin ?? null, definingType: m.definingType ?? null,
      superTarget: m.superTarget ?? null,
      params: m.params.map(p => ({
        name: p.name,
        direction: p.direction,
        optional: p.optional,
        type: p.type.raw
      }))
    })),
    aliases: n.aliases, events: n.events.map((e) => e.name),
  }));
  return JSON.stringify(
    { root: model.root, linearization: model.linearization, nodes, edges: model.edges },
    null, 2,
  );
}

export function buildTransformationPrompt(input: BuildPromptInput): string {
  const { model, sources, detectedConstructs } = input;

  const sqlMetadata: string[] = [];
  const detectedQuirkTypes = new Set<string>();

  for (const src of sources) {
    const selects = extractSelects(src.content);
    for (const sel of selects) {
      const selModel = parseSelect(sel.text, src.file, sel.line);
      const cdsMatch = matchCdsView(selModel);
      const quirks = selModel.quirks.map((q) => q.type);
      quirks.forEach((q) => detectedQuirkTypes.add(q));

      const lineMeta = [
        `- SQL SELECT in file ${src.file} (line ${sel.line}):`,
        `  Original ABAP: "${sel.text}"`,
        cdsMatch
          ? `  Matched CDS View: ${cdsMatch.view} (Confidence: ${cdsMatch.confidence}, Exact Match: ${cdsMatch.exact})`
          : `  No released CDS View match found. Replicate join structure.`,
        quirks.length ? `  Detected Quirks: ${quirks.join(', ')}` : `  No SQL quirks detected.`,
      ].join('\n');
      sqlMetadata.push(lineMeta);
    }
  }

  const sqlRulesText = detectedQuirkTypes.size > 0
    ? quirkRulesFor(Array.from(detectedQuirkTypes) as any)
    : 'No SQL quirks detected.';

  const systemFacts = [
    `You are transforming ABAP to TypeScript for the Clean-Core.io platform.`,
    ``,
    `The class hierarchy below is RESOLVED FACT (deterministically computed). Do NOT`,
    `re-infer inheritance, redefinitions, interface mappings or constructor chains —`,
    `use exactly what is given:`,
    `--- RESOLVED HIERARCHY (IR) ---`,
    serializeHierarchy(model),
    `--- END IR ---`,
    ``,
    `--- DETECTED SQL QUERY METADATA ---`,
    sqlMetadata.join('\n\n') || 'No SQL queries detected in source code.',
    `--- END SQL METADATA ---`,
    ``,
    `--- SQL QUIRK RULES & GROUNDING ---`,
    sqlRulesText,
    `--- END SQL QUIRK RULES ---`,
    ``,
    `Mapping rules: inheritance → extends; interfaces → implements; REDEFINITION →`,
    `method override; super->m() → super.m(); CONSTRUCTOR chain → super(...) first;`,
    `CLASS-CONSTRUCTOR → static init; ALIASES → concrete method + alias accessor;`,
    `visibility → TS access modifiers; events → typed emitter. FINAL/FRIENDS have no`,
    `TS equivalent → emit + flag as documented relaxations.`,
    ``,
    `For EVERY construct you translate that is partial or not-supported, you MUST add`,
    `an inline marker at the exact line, e.g.:`,
    `//  ⚠️ [CC-PARTIAL: dynamic-call] <reason>. See ${HOW_IT_WORKS_BASE}#dynamic-call`,
    `and a corresponding entry in "findings". Never silently downgrade.`,
    ``,
    howItWorksReferences(detectedConstructs),
    ``,
    OUTPUT_CONTRACT,
  ].join('\n');

  const bodies = sources
    .map((s) => `// FILE: ${s.file}\n${s.content}`)
    .join('\n\n');

  return `${systemFacts}\n\n--- ABAP METHOD BODIES TO TRANSLATE ---\n${bodies}`;
}
