REPORT zcc_ref_026.
PARAMETERS p_id TYPE c LENGTH 10.
PARAMETERS p_route TYPE c LENGTH 20.
PARAMETERS p_abort AS CHECKBOX.
START-OF-SELECTION.
  CALL FUNCTION 'Z_CC_DECISION_UPD'
    IN UPDATE TASK
    EXPORTING iv_case_id = p_id
              iv_route   = p_route.
  WRITE / 'REGISTERED'.
  IF p_abort = 'X'.
    ROLLBACK WORK.
    WRITE / 'DISCARDED'.
  ELSE.
    COMMIT WORK.
    WRITE / 'COMMITTED'.
  ENDIF.
