import pluginNext from "@next/eslint-plugin-next";
import tsParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import pluginReactHooks from "eslint-plugin-react-hooks";

/**
 * The lint gate, and what it was.
 *
 * This file imported three plugins and enabled the rules of exactly one. The
 * `rules` block spread only the Next presets; `@typescript-eslint` and
 * `react-hooks` were registered and switched on for nothing. `npm run lint` is a
 * required step of the deploy pipeline (`.github/workflows/deploy.yml`), so for
 * every release since, the pipeline reported a green check for a check it was
 * not performing. A ref written during render, a dead profile mutation whose own
 * comment claimed it re-rendered the page, and four consts read out of the
 * temporal dead zone all walked through it.
 *
 * Turning the two presets on surfaced 706 problems at once. They are sorted, not
 * silenced:
 *
 *   error — anything that describes a defect. Every one of them is fixed, so the
 *           gate is red the moment a new one appears.
 *   warn  — two hygiene classes, 664 of the 706. `npm run lint` pins the count
 *           with `--max-warnings`, which makes the backlog a number in the repo
 *           that can go down and cannot go up.
 *   off   — one rule that reports on an optimisation this project does not run.
 */
export default [
  {
    ignores: [
      "tmp/**",
      ".next/**",
      "dist/**",
      "out/**",
      "build/**",
      "scratch/**",
      // Regenerated by Next on every build — including the triple-slash
      // reference the TS preset objects to.
      "next-env.d.ts",
      // A separate Remotion project. It ships nothing to clean-core.io and is
      // not built by the pipeline; linting it only produced findings nobody
      // could act on from here.
      "clean-core-video/**",
    ],
  },
  {
    files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      "@next/next": pluginNext,
      "@typescript-eslint": tsPlugin,
      "react-hooks": pluginReactHooks,
    },
    rules: {
      ...pluginNext.configs.recommended.rules,
      ...pluginNext.configs["core-web-vitals"].rules,
      ...tsPlugin.configs.recommended.rules,
      ...pluginReactHooks.configs.recommended.rules,

      // --- Parked. Counted, pinned by --max-warnings, and worth a pass of
      // their own rather than a paragraph in a release commit.
      "@typescript-eslint/no-explicit-any": "warn", // 365 at the time of writing
      "@typescript-eslint/no-unused-vars": "warn", // 274
      "react-hooks/set-state-in-effect": "warn", // 25

      // The React Compiler is not enabled in next.config.mjs. "Compilation
      // skipped" is therefore a report about an optimisation that never runs;
      // turn this back on the day the compiler is switched on.
      "react-hooks/preserve-manual-memoization": "off",

      // An ignore that explains itself is a decision. A bare one is a shrug.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        { "ts-ignore": "allow-with-description" },
      ],
    },
  },
  {
    // Node-side files that no bundler ever sees. `require` is a module-style
    // rule, and the style it argues for only buys anything where a bundler has
    // to follow the import. In a one-off script or a Playwright spec it buys
    // nothing, and rewriting a dozen working files to earn a green tick would
    // be the tick wagging the code.
    files: ["scripts/**", "tests/**"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];
