import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

/**
 * What the Terms, and every summary of them, say about who produced a result.
 *
 * Two QA findings of the v2.20.0 full review (6b83ef361e80, c9ab2c6a6c1c): the
 * Terms said "Modernization analyses and source code are generated automatically
 * by generative AI models", the sign-up disclaimer said "Parts of every analysis
 * [...] are written by a language model", and the Terms summary said "All code
 * and analyses are generated by AI models". None of that is true of the product:
 * the findings, the route and the Clean Core Score come from the deterministic
 * engine (`lib/model-stages.ts`, the `analyze` description), the model stages
 * can be switched off one by one, and an analysis with all of them off is still
 * a complete, signed run.
 *
 * Sonny, 30.09.2026: a new Terms version (v2.2.0, with 3.0) that says which part
 * is which, and both summaries in step with it. The three places are held here
 * together, because a summary that drifts from the contract is the same untrue
 * sentence with a smaller font.
 */

const ROOT = path.resolve(__dirname, '..');
const read = (rel: string) => fs.readFileSync(path.resolve(ROOT, rel), 'utf8');

/** JSX to prose: tags and entities out, whitespace flattened. */
function prose(src: string): string {
  return src
    .replace(/<[^>]+>/g, ' ')
    .replace(/&mdash;/g, '—')
    .replace(/&apos;|&rsquo;/g, "'")
    .replace(/\s+/g, ' ');
}

const PLACES = {
  terms: 'app/terms/page.tsx',
  signup: 'components/LandingModals.tsx',
  onboarding: 'components/UserOnboarding.tsx',
} as const;

/** Sentences that attribute the whole analysis to a model. */
const FORBIDDEN: RegExp[] = [
  /Modernization analyses and source codes? (?:are|is) (?:generated|synthesized) automatically/i,
  /All (?:code and )?analyses are (?:generated|powered|written) by (?:AI|Generative AI|a language model)/i,
  /All analyses are powered by Generative AI/i,
  /Parts of every analysis/i,
  /analyses (?:and source codes? )?are synthesized automatically using Generative AI/i,
];

test('no Terms text or summary attributes the whole analysis to a model', () => {
  for (const file of Object.values(PLACES)) {
    const text = prose(read(file));
    for (const pattern of FORBIDDEN) {
      expect(
        text,
        `${file} says the analysis is model-generated (${pattern}). The findings, the route and the score are the ` +
          "deterministic engine's; only the model steps are written by a language model.",
      ).not.toMatch(pattern);
    }
  }
});

test('each of them names both halves', () => {
  for (const file of Object.values(PLACES)) {
    const text = prose(read(file));
    expect(text, `${file} no longer says the findings come from the deterministic engine`).toMatch(
      /deterministic (?:engine|analysis|results)/i,
    );
    expect(text, `${file} no longer says the findings are computed without a model`).toMatch(
      /without a (?:generative AI model|language model)/i,
    );
    expect(text, `${file} no longer says which output a model writes`).toMatch(
      /(?:generated automatically by generative AI models|written by a language model)/i,
    );
  }
});

test('the rendered sign-up summary and the Terms agree', async ({ page }) => {
  // The source check above is the fast one; this is the one a reader meets.
  await page.goto('/terms', { waitUntil: 'domcontentloaded' });
  const terms = (await page.locator('main').innerText()).replace(/\s+/g, ' ');
  expect(terms).toContain('Deterministic results');
  expect(terms).toContain('without a generative AI model');
  expect(terms).toContain('Model-generated output');
  expect(terms).not.toMatch(/Modernization analyses and source code are generated automatically by generative AI models/);

  await page.goto('/?auth=signup', { waitUntil: 'domcontentloaded' });
  const disclaimer = page.getByText('Findings, route and score come from a deterministic engine', { exact: false });
  await expect(disclaimer, 'the sign-up disclaimer does not say what the engine computes').toBeVisible({
    timeout: 60000,
  });
});
