'use client';

import { useState } from 'react';

// ── Real abapGit-compatible file contents ──
// Based on the Sales Order (VBAK) transformation example from the Showroom.
// This is a genuine, business-relevant Clean Core modernization:
//   Legacy: SELECT ... FROM VBAK (non-released table)
//   Modern: CDS View consuming I_SalesOrder (released SAP API)

const FILES = {
  'src/zi_salesordercustom.ddls.asddls': `@AbapCatalog.sqlViewName: 'ZV_SLSORDCUST'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Clean Core Sales Order Projection'
@VDM.viewType: #CONSUMPTION

define view entity ZI_SalesOrderCustom
  as select from I_SalesOrder
{
  key SalesOrder          as SalesOrderNumber,
      SalesOrderType      as OrderType,
      SalesOrganization   as SalesOrg,
      DistributionChannel as DistChannel,
      OrganizationDivision as Division,
      SoldToParty         as Customer,
      CreationDate        as OrderDate,
      TotalNetAmount      as NetAmount,
      TransactionCurrency as Currency,
      OverallSDProcessStatus as ProcessStatus
}
where SalesOrderType = 'OR'
`,

  'src/zcl_salesorder_read.clas.abap': `"! <p class="shorttext synchronized">Clean Core Sales Order Reader</p>
"! Replaces legacy SELECT FROM VBAK with released I_SalesOrder CDS view.
"! Generated by Clean-Core.io Engine v1.10.0
CLASS zcl_salesorder_read DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES: BEGIN OF ty_order,
             sales_order_number TYPE vbeln,
             order_type         TYPE auart,
             sales_org          TYPE vkorg,
             customer           TYPE kunag,
             order_date         TYPE erdat,
             net_amount         TYPE netwr,
             currency           TYPE waers,
             process_status     TYPE string,
           END OF ty_order,
           tt_orders TYPE STANDARD TABLE OF ty_order WITH EMPTY KEY.

    "! Read open standard sales orders via released CDS view
    "! @parameter rt_orders | Table of sales orders (type OR)
    METHODS get_open_orders
      RETURNING VALUE(rt_orders) TYPE tt_orders.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_salesorder_read IMPLEMENTATION.

  METHOD get_open_orders.
    " Clean Core compliant: Uses released CDS view instead of VBAK
    SELECT SalesOrderNumber,
           OrderType,
           SalesOrg,
           Customer,
           OrderDate,
           NetAmount,
           Currency,
           ProcessStatus
      FROM ZI_SalesOrderCustom
      INTO CORRESPONDING FIELDS OF TABLE @rt_orders.
  ENDMETHOD.

ENDCLASS.
`,

  'src/zcl_salesorder_read.clas.xml': `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_CLAS" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <VSEOCLASS>
    <CLSNAME>ZCL_SALESORDER_READ</CLSNAME>
    <LANGU>E</LANGU>
    <DESCRIPT>Clean Core Sales Order Reader</DESCRIPT>
    <STATE>1</STATE>
    <CLSCCINCL>X</CLSCCINCL>
    <FIXPT>X</FIXPT>
    <UNICODE>X</UNICODE>
   </VSEOCLASS>
  </asx:values>
 </asx:abap>
</abapGit>
`,

  'src/ltcl_salesorder.clas.testclasses.abap': `"! <p class="shorttext synchronized">Unit Tests for ZI_SalesOrderCustom</p>
"! Uses CDS Test Environment doubles for isolated testing.
"! Generated by Clean-Core.io Engine v1.10.0
CLASS ltcl_salesorder DEFINITION FINAL FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    CLASS-DATA environment TYPE REF TO if_cds_test_environment.
    CLASS-METHODS class_setup.
    CLASS-METHODS class_teardown.
    METHODS test_only_type_or_returned FOR TESTING.
    METHODS test_field_mapping FOR TESTING.
    METHODS test_empty_result FOR TESTING.

ENDCLASS.

CLASS ltcl_salesorder IMPLEMENTATION.

  METHOD class_setup.
    environment = cl_cds_test_environment=>create(
      i_for_entity = 'ZI_SALESORDERCUSTOM' ).
  ENDMETHOD.

  METHOD class_teardown.
    environment->destroy( ).
  ENDMETHOD.

  METHOD test_only_type_or_returned.
    " Arrange — insert test double data with mixed order types
    DATA lt_mock TYPE STANDARD TABLE OF I_SalesOrder.
    lt_mock = VALUE #(
      ( SalesOrder = '0000000100' SalesOrderType = 'OR'
        TotalNetAmount = '15000.00' TransactionCurrency = 'EUR' )
      ( SalesOrder = '0000000200' SalesOrderType = 'RE'
        TotalNetAmount = '8500.00' TransactionCurrency = 'EUR' )
      ( SalesOrder = '0000000300' SalesOrderType = 'OR'
        TotalNetAmount = '22000.00' TransactionCurrency = 'USD' ) ).
    environment->insert_test_data( i_data = lt_mock ).

    " Act — read via CDS projection
    DATA lt_result TYPE STANDARD TABLE OF ZI_SalesOrderCustom.
    SELECT * FROM ZI_SalesOrderCustom INTO TABLE @lt_result.

    " Assert — only type OR should pass the filter (2 of 3)
    cl_abap_unit_assert=>assert_equals(
      act = lines( lt_result )
      exp = 2
      msg = 'Filter should return only OR-type orders' ).

    environment->clear_doubles( ).
  ENDMETHOD.

  METHOD test_field_mapping.
    " Arrange
    DATA lt_mock TYPE STANDARD TABLE OF I_SalesOrder.
    lt_mock = VALUE #(
      ( SalesOrder = '0000000500' SalesOrderType = 'OR'
        CreationDate = '20260115' TotalNetAmount = '42000.00'
        TransactionCurrency = 'EUR' ) ).
    environment->insert_test_data( i_data = lt_mock ).

    " Act
    DATA lt_result TYPE STANDARD TABLE OF ZI_SalesOrderCustom.
    SELECT * FROM ZI_SalesOrderCustom INTO TABLE @lt_result.

    " Assert — verify field aliases are correctly mapped
    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-SalesOrderNumber
      exp = '0000000500'
      msg = 'SalesOrder should map to SalesOrderNumber' ).
    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-NetAmount
      exp = '42000.00'
      msg = 'TotalNetAmount should map to NetAmount' ).

    environment->clear_doubles( ).
  ENDMETHOD.

  METHOD test_empty_result.
    " Arrange — insert only non-OR orders
    DATA lt_mock TYPE STANDARD TABLE OF I_SalesOrder.
    lt_mock = VALUE #(
      ( SalesOrder = '0000000900' SalesOrderType = 'RE' )
      ( SalesOrder = '0000000901' SalesOrderType = 'BV' ) ).
    environment->insert_test_data( i_data = lt_mock ).

    " Act
    DATA lt_result TYPE STANDARD TABLE OF ZI_SalesOrderCustom.
    SELECT * FROM ZI_SalesOrderCustom INTO TABLE @lt_result.

    " Assert — no OR-type orders should yield empty result
    cl_abap_unit_assert=>assert_initial(
      act = lt_result
      msg = 'No OR-type orders means empty result' ).

    environment->clear_doubles( ).
  ENDMETHOD.

ENDCLASS.
`,

  '.abapgit.xml': `<?xml version="1.0" encoding="utf-8"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <DATA>
   <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
   <STARTING_FOLDER>/src/</STARTING_FOLDER>
   <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
   <IGNORE>
    <item>/.gitignore</item>
    <item>/LICENSE</item>
    <item>/README.md</item>
    <item>/package.json</item>
    <item>/.travis.yml</item>
   </IGNORE>
  </DATA>
 </asx:values>
</asx:abap>
`,

  'README.md': `# ZI_SalesOrderCustom — Clean Core Transformation Sample

> Generated by [Clean-Core.io](https://clean-core.io) Engine v1.10.0 · June 2026

## What This Package Contains

This is a real abapGit-compatible package demonstrating a Clean Core transformation
from legacy direct VBAK table access to a released CDS view consuming \`I_SalesOrder\`.

### Before (Legacy)
\`\`\`abap
" Direct table read — violates Clean Core
SELECT vbeln, erdat, netwr
  FROM vbak
  INTO TABLE @DATA(lt_orders)
  WHERE auart = 'OR'.
\`\`\`

### After (Clean Core)
- **CDS View**: \`ZI_SalesOrderCustom\` — consumes released \`I_SalesOrder\`
- **Reader Class**: \`ZCL_SALESORDER_READ\` — typed access via CDS projection
- **Unit Tests**: 3 ABAP Unit tests with CDS Test Environment doubles

## How to Import

1. Open Eclipse ADT
2. Open the abapGit view (**Window → Show View → Other → abapGit Repositories**)
3. Click **"Import ZIP"** or link this as a local repository
4. Assign to your development package (e.g., \`ZCLEAN_CORE_DEMO\`)
5. Activate all objects
6. Run Unit Tests: Right-click \`ZCL_SALESORDER_READ\` → **Run As → ABAP Unit Test**

## Clean Core Compliance

| Check | Status |
|-------|--------|
| No direct table access (VBAK, BSEG, etc.) | ✅ Compliant |
| Uses released CDS views only | ✅ I_SalesOrder |
| CDS Test Environment doubles | ✅ 3 tests |
| abapGit-compatible structure | ✅ Standard layout |

---
*This sample is provided as-is for evaluation purposes. Visit [clean-core.io](https://clean-core.io) to transform your own legacy code.*
`,
};

export default function SamplePackageDownload() {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();

      // Add all files to the ZIP
      for (const [path, content] of Object.entries(FILES)) {
        zip.file(path, content);
      }

      // Generate and download
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'ZI_SalesOrderCustom_CleanCore_abapGit.zip';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Download failed:', err);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div
      data-testid="sample-package-download"
      className="mt-12 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 rounded-2xl border border-slate-700/50 overflow-hidden shadow-2xl shadow-black/20"
    >
      <div className="p-6 sm:p-8 md:p-10">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
          {/* Left: Description */}
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-3">
              <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-emerald-300 bg-emerald-500/10 text-[10px] font-black uppercase tracking-wider border border-emerald-500/20">
                Free Download · No Login
              </span>
            </div>
            <h3 className="text-xl sm:text-2xl font-black text-white tracking-tight mb-2">
              Download a Real abapGit Package
            </h3>
            <p className="text-sm text-slate-400 font-medium leading-relaxed max-w-xl">
              A complete, importable abapGit package generated by the Clean-Core Engine.
              Contains the Sales Order (VBAK → I_SalesOrder) CDS view, typed reader class,
              and 3 ABAP Unit tests with CDS Test Environment doubles.
              Import it directly into Eclipse ADT.
            </p>

            {/* File list preview */}
            <div className="mt-4 flex flex-wrap gap-2">
              {[
                { name: 'zi_salesordercustom.ddls.asddls', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20' },
                { name: 'zcl_salesorder_read.clas.abap', color: 'text-blue-400 bg-blue-500/10 border-blue-500/20' },
                { name: 'ltcl_salesorder.clas.testclasses.abap', color: 'text-violet-400 bg-violet-500/10 border-violet-500/20' },
                { name: '.abapgit.xml', color: 'text-slate-300 bg-slate-500/10 border-slate-500/20' },
              ].map(file => (
                <span
                  key={file.name}
                  className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-mono font-bold border ${file.color}`}
                >
                  <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  {file.name}
                </span>
              ))}
            </div>
          </div>

          {/* Right: Download Button */}
          <div className="shrink-0 w-full lg:w-auto">
            <button
              onClick={handleDownload}
              disabled={isDownloading}
              className="w-full lg:w-auto group relative inline-flex items-center justify-center gap-3 bg-gradient-to-r from-emerald-600 to-emerald-500 hover:from-emerald-500 hover:to-emerald-400 disabled:from-slate-600 disabled:to-slate-500 text-white px-8 py-4 rounded-2xl font-black text-sm uppercase tracking-widest transition-all duration-300 shadow-xl shadow-emerald-500/25 hover:shadow-emerald-500/40 hover:scale-[1.02] active:scale-[0.98] disabled:cursor-wait disabled:shadow-none"
            >
              {isDownloading ? (
                <>
                  <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                  </svg>
                  Generating ZIP…
                </>
              ) : (
                <>
                  <svg className="w-5 h-5 group-hover:translate-y-0.5 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download abapGit Package
                  <span className="text-[9px] font-bold text-emerald-200/70 uppercase tracking-normal ml-1">
                    (.zip)
                  </span>
                </>
              )}
            </button>
            <p className="text-[10px] text-slate-500 font-medium text-center mt-2">
              ~5 KB · Ready for Eclipse ADT import
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
