import type { AbapEvidenceReport } from './abap/evidence-model';
import { anchorInstruction } from './abap/narrative-anchors';
import type { ExtensibilityRouteReport } from './abap/extensibility-router';

/**
 * The prompt of the Analyze stage, assembled in one place so it can be tested as a whole.
 *
 * It lived inline in the page, and the citation rule had two copies: the CITATIONS block from
 * narrative-anchors.ts, and a field comment that still said `[F-id]` after the engine's ids had been
 * `CC-…` all along. The parser rejected every citation the comment asked for, and the tests only
 * looked at the block (QA review of a0c108513165). The field comments now point at the block.
 */
export function buildAnalysisPrompt({
  targetDeployment,
  evidenceReport,
  routeReport,
  code,
}: {
  targetDeployment: string | null | undefined;
  evidenceReport: AbapEvidenceReport;
  routeReport: ExtensibilityRouteReport;
  code: string;
}): string {
  return `You are analyzing a legacy SAP ABAP custom codebase for modernization. The customer has defined their target operating model as: SAP S/4HANA Cloud, ${targetDeployment === 'public' ? 'Public Edition (strict SaaS, zero modifications allowed)' : 'Private Edition / RISE (3-Tier Extensibility Model, allowing custom Tier 2 API wrappers)'}.

Here is the deterministic Evidence Report generated by our static analysis parser. You MUST treat this as the absolute technical ground-truth and base your business/narrative assessment strictly on this data. Do NOT invent other database tables, legacy patterns, or findings that are not listed here:
${JSON.stringify(evidenceReport, null, 2)}
      
Analyze the legacy SAP ABAP code and the evidence findings to provide a highly practical, down-to-earth IT and Business assessment. You must return your output strictly in JSON format. Do not include any markdown formatting, HTML, or explanations outside the JSON object. The JSON must exactly match this TypeScript schema, and you MUST populate the fields 'cleanCoreScore' and 'extensibilityRouting' with the exact pre-calculated values provided below:

No field of this output states an amount of money — no cost, saving, price, budget or ROI in any currency. Nothing in this analysis rests on approved cost assumptions, and an amount you write is removed before anyone reads it.

${anchorInstruction(evidenceReport.findings, code.split(/\r?\n/).length)}

interface AnalysisData {
  projectTitle: string;
  cleanCoreScore: number; // YOU MUST USE EXACTLY THIS VALUE: ${routeReport.cleanCoreScore}
  summary: string; // Plain english business executive summary. Every sentence that states something about THIS program must end with an anchor in one of the forms listed under CITATIONS above. General advice stays uncited.
  asIsContext: string; // Describe what the legacy program does. Same citation rule: anchor every claim about this code.
  standardFit: {
    potential: 'High' | 'Medium' | 'Low';
    targetStandardProcess: string; 
    rationale: string; 
  };
  gaps: Array<{
    title: string; 
    severity: 'High' | 'Medium' | 'Low'; 
    strategy: string; 
    rationale: string; 
    complexity: 'High' | 'Medium' | 'Low'; 
  }>;
  recommendations: {
    keepCoreClean: string; // STEP 1: What standard SAP replacement exists? Name the EXACT standard object (e.g. "Use released CDS view I_Customer instead of SELECT on KNA1"). Mark each API as "(Catalog Match)", "(Candidate)", or "(Needs Validation)" based on whether you are certain the API exists and covers the use case. Do NOT say "rewrite" here — only name the standard alternative.
    decommissioning: string; // STEP 2: What legacy objects can be RETIRED after the standard alternative from Step 1 is adopted and validated? Never say "delete" — use "retire after replacement validation, data migration assessment, and business sign-off". Be explicit about which custom objects are candidates for retirement. Must be consistent with keepCoreClean.
    cloudReadiness: string; // STEP 3: If Step 1 fully replaces the legacy code, state "No rewrite needed — standard replacement covers all functionality." If Step 1 only partially covers, describe ONLY the remaining gap that needs ABAP Cloud or Tier 2 wrapping. For complex programs, describe a HYBRID approach: which components go to RAP/In-App, which to CAP/BTP, which to Integration Suite/Event Mesh, and which to Fiori/UI5. NEVER contradict Step 1 or Step 2.
  };
  strategicNextSteps: string[]; 
  extensibilityRouting: {
    // YOU MUST USE EXACTLY THESE PRE-CALCULATED VALUES:
    recommendedRoute: "${routeReport.recommendedRoute}";
    confidenceScore: ${routeReport.confidenceScore};
    rationale: "${routeReport.rationale.replace(/"/g, '\\"')}";
    targetArtifact: "${routeReport.targetArtifact}";
    decisionTreeCheckpoints: ${JSON.stringify(routeReport.checkpoints)};
    comparativeAnalysis: ${JSON.stringify(routeReport.comparativeAnalysis)};
  };
  businessValueAnalysis: {
    legacyAssetScore: number; 
    technicalDebtLevel: 'Low' | 'Medium' | 'High';
    valueDrivers: string[]; 
    plainEnglishActionPlan: string[]; // No money: no costs, savings, ROI or currency amounts anywhere in this object — nothing here rests on approved cost assumptions.
  };
}

Legacy Code to Analyze:
${code}`;
}
