/**
 * Compliance Audit Pack Generator (v1.17.0)
 *
 * Generates an exportable ZIP containing structured evidence for
 * architecture governance reviews, compliance audits, and enterprise
 * decision documentation.
 *
 * v2.0: The pack (evidence files + manifest with SHA-256 hashes + HMAC-SHA256
 * signature) is generated and signed entirely server-side by
 * /api/audit-pack/create, so the signature attests to server content — not to
 * client-supplied hashes. The legacy /api/export/sign endpoint is retired (410).
 *
 * Security: This module never includes secrets, credentials, API keys,
 * or unmasked tenant URLs in the export. Only hashes, timestamps,
 * model identifiers, and architecture decisions are included.
 */

import type { Project, WorklistItem } from '@/lib/types';
import { APP_VERSION, APP_RELEASE_DATE } from '@/lib/version';

interface ManifestFile {
  path: string;
  sha256: string;
  bytes: number;
}

export interface AuditPackManifest {
  version: string;
  runId: string;
  projectId: string;
  generatedAt: string;
  engineVersion: string;
  sapApiCatalogVersion: string;
  files: ManifestFile[];
  manifestHash: string;
  signed: boolean;
  signature: string;
  signatureError?: string;
  runHash?: string;
}

const ARCH_LABELS: Record<string, string> = {
  rap: 'In-App ABAP Cloud (RAP)',
  cap: 'Side-by-Side BTP (CAP)',
  integration: 'SAP Integration Suite',
  event: 'SAP Event Mesh',
  retire: 'Retire / Decommission',
};

/**
 * Escape a value for safe interpolation into the HTML/Word executive summary.
 * Project/user/AI-supplied fields (name, approver email, file name, …) must never
 * be able to inject markup or active content into the exported document.
 */
function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Guard a CSV cell against spreadsheet formula injection: a value that a
 * spreadsheet would evaluate (leading =, +, -, @, tab, or CR) is prefixed with a
 * single quote, then quoted and its inner quotes doubled per RFC 4180.
 */
function csvCell(value: unknown): string {
  let s = String(value ?? '');
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return `"${s.replace(/"/g, '""')}"`;
}

/** Normalise a value for a Markdown table cell (escape pipes / collapse newlines). */
function mdCell(value: unknown): string {
  return String(value ?? '—').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim() || '—';
}

export function generateExecutiveSummary(project: Project): string {
  const fp = project.auditMetadata?.inputFingerprint;
  const mc = project.auditMetadata?.modelCard;
  const arch = project.targetArchitecture ? ARCH_LABELS[project.targetArchitecture] || project.targetArchitecture : 'Not determined';
  const approved = project.approvedByArchitect ? '✓ Approved' : '○ Pending';
  const approver = project.approvedBy ? ` by ${project.approvedBy}` : '';
  const signOffDate = project.architectSignOffAt
    ? new Date(project.architectSignOffAt as string).toISOString()
    : '—';

  return `# Compliance Audit Pack — Executive Summary

> Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}
> This document is a machine-generated draft for review. It does not replace a formal architecture sign-off.

---

## Project Overview

| Field | Value |
|---|---|
| Project Name | ${mdCell(project.name)} |
| Analysis Status | ${mdCell(project.status || 'unknown')} |
| Clean Core Score | ${project.cleanCoreScore ?? '—'}/100 |
| Complexity Score | ${project.complexityScore ?? '—'}/100 |
| Criticality Score | ${project.criticalityScore ?? '—'}/100 |
| Target Architecture | ${mdCell(arch)} |
| Architect Sign-Off (self-attested) | ${mdCell(approved + approver)} |
| Sign-Off Date | ${mdCell(signOffDate)} |
| Extensibility Route | ${mdCell(project.extensibilityRoute || '—')} |

## Input Summary

| Field | Value |
|---|---|
| File Name | ${mdCell(fp?.fileName || '—')} |
| Object Type | ${mdCell(fp?.objectType || '—')} |
| Lines of Code | ${fp?.lineCount ?? '—'} |
| Input Size | ${fp?.byteSize ? `${(fp.byteSize / 1024).toFixed(1)} KB` : '—'} |
| SHA-256 Fingerprint | \`${mdCell(fp?.sha256 || '—')}\` |
| Upload Timestamp | ${mdCell(fp?.uploadedAt || '—')} |

## Engine Metadata

| Field | Value |
|---|---|
| Platform Version | ${mdCell(mc?.engineVersion || APP_VERSION)} |
| SAP API Catalog | ${mdCell((mc as any)?.catalogVersion || '2024.FPS02')} |
| Model Provider | ${mdCell(mc?.provider || 'google-gemini')} |
| Model | ${mdCell(mc?.model || '—')} |
| BYOK Used | ${mc?.byokUsed ? 'Yes' : 'No'} |
| Analysis Timestamp | ${mdCell(mc?.analysisTimestamp || '—')} |
| Design Timestamp | ${mdCell(mc?.designTimestamp || '—')} |
| Transformation Timestamp | ${mdCell(mc?.transformationTimestamp || '—')} |

---

## Audit Pack Disclaimer

This audit pack documents an automated modernization analysis. The results represent a technical and architectural decision aid. They do not replace a formal architecture sign-off, a data protection review, or a production SAP acceptance test.

Generated code is a draft for review — not a production-ready deliverable.
`;
}

export function generateExecutiveSummaryDoc(project: Project): string {
  const fp = project.auditMetadata?.inputFingerprint;
  const mc = project.auditMetadata?.modelCard;
  const arch = project.targetArchitecture ? ARCH_LABELS[project.targetArchitecture] || project.targetArchitecture : 'Not determined';
  const approved = project.approvedByArchitect ? '✓ Approved' : '○ Pending';
  const approver = project.approvedBy ? ` by ${project.approvedBy}` : '';
  const signOffDate = project.architectSignOffAt
    ? new Date(project.architectSignOffAt as string).toISOString()
    : '—';
  const score = project.cleanCoreScore ?? '—';
  const complexity = project.complexityScore ?? '—';
  const criticality = project.criticalityScore ?? '—';

  return `<html xmlns:o='urn:schemas-microsoft-com:office:office' 
      xmlns:w='urn:schemas-microsoft-com:office:word' 
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <title>Compliance Audit Pack — Executive Summary</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 11pt; line-height: 1.5; color: #333333; margin: 1in; }
    h1 { font-family: 'Calibri Light', sans-serif; font-size: 24pt; color: #006b2c; border-bottom: 2px solid #006b2c; padding-bottom: 5px; margin-top: 0; }
    h2 { font-family: 'Calibri Light', sans-serif; font-size: 16pt; color: #00873a; margin-top: 20px; border-bottom: 1px solid #D3D3D3; padding-bottom: 3px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 20px; }
    th { background-color: #006b2c; color: #ffffff; text-align: left; font-weight: bold; padding: 6px 10px; border: 1px solid #D3D3D3; }
    td { padding: 6px 10px; border: 1px solid #D3D3D3; vertical-align: top; }
    tr:nth-child(even) td { background-color: #F0Fdf4; }
    blockquote { border-left: 4px solid #00873a; padding-left: 10px; margin-left: 0; color: #595959; font-style: italic; }
    code { font-family: 'Consolas', monospace; background-color: #F2F2F2; padding: 2px 4px; font-size: 10pt; }
    .footer { font-size: 9pt; color: #7F7F7F; text-align: right; margin-top: 40px; border-top: 1px solid #D3D3D3; padding-top: 5px; }
  </style>
</head>
<body>
  <h1>Compliance Audit Pack — Executive Summary</h1>
  <blockquote>
    Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}<br/>
    This document is a machine-generated draft for review. It does not replace a formal architecture sign-off.
  </blockquote>

  <h2>Project Overview</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Project Name</td><td>${escapeHtml(project.name)}</td></tr>
      <tr><td>Analysis Status</td><td>${escapeHtml(project.status || 'unknown')}</td></tr>
      <tr><td>Clean Core Score</td><td>${score}/100</td></tr>
      <tr><td>Complexity Score</td><td>${complexity}/100</td></tr>
      <tr><td>Criticality Score</td><td>${criticality}/100</td></tr>
      <tr><td>Target Architecture</td><td>${escapeHtml(arch)}</td></tr>
      <tr><td>Architect Sign-Off (self-attested)</td><td>${escapeHtml(approved + approver)}</td></tr>
      <tr><td>Sign-Off Date</td><td>${escapeHtml(signOffDate)}</td></tr>
      <tr><td>Extensibility Route</td><td>${escapeHtml(project.extensibilityRoute || '—')}</td></tr>
    </tbody>
  </table>

  <h2>Input Summary</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>File Name</td><td>${escapeHtml(fp?.fileName || '—')}</td></tr>
      <tr><td>Object Type</td><td>${escapeHtml(fp?.objectType || '—')}</td></tr>
      <tr><td>Lines of Code</td><td>${fp?.lineCount ?? '—'}</td></tr>
      <tr><td>Input Size</td><td>${fp?.byteSize ? `${(fp.byteSize / 1024).toFixed(1)} KB` : '—'}</td></tr>
      <tr><td>SHA-256 Fingerprint</td><td><code>${escapeHtml(fp?.sha256 || '—')}</code></td></tr>
      <tr><td>Upload Timestamp</td><td>${escapeHtml(fp?.uploadedAt || '—')}</td></tr>
    </tbody>
  </table>

  <h2>Engine Metadata</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Platform Version</td><td>${escapeHtml(mc?.engineVersion || APP_VERSION)}</td></tr>
      <tr><td>Model Provider</td><td>${escapeHtml(mc?.provider || 'google-gemini')}</td></tr>
      <tr><td>Model</td><td>${escapeHtml(mc?.model || '—')}</td></tr>
      <tr><td>BYOK Used</td><td>${mc?.byokUsed ? 'Yes' : 'No'}</td></tr>
      <tr><td>Analysis Timestamp</td><td>${escapeHtml(mc?.analysisTimestamp || '—')}</td></tr>
      <tr><td>Design Timestamp</td><td>${escapeHtml(mc?.designTimestamp || '—')}</td></tr>
      <tr><td>Transformation Timestamp</td><td>${escapeHtml(mc?.transformationTimestamp || '—')}</td></tr>
    </tbody>
  </table>

  <h2>Audit Pack Disclaimer</h2>
  <p>This audit pack documents an automated modernization analysis. The results represent a technical and architectural decision aid. They do not replace a formal architecture sign-off, a data protection review, or a production SAP acceptance test.</p>
  <p>Generated code is a draft for review — not a production-ready deliverable.</p>

  <div class="footer">
    Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}
  </div>
</body>
</html>`;
}

export function generateDecisionRecord(project: Project): object {
  return {
    projectName: project.name,
    generatedAt: new Date().toISOString(),
    engineVersion: APP_VERSION,
    recommendation: {
      targetArchitecture: project.targetArchitecture || null,
      originalRecommendation: project.originalRecommendation || null,
      confidence: project.recommendationConfidence ?? null,
      justification: project.recommendationJustification || null,
    },
    architectReview: {
      // Self-attestation: the sign-off is recorded from the signed-in user's own
      // client session, not verified by a separate approver or an org role model.
      // It is a decision record, not a formal organizational approval.
      attestationType: 'self-attested',
      approved: project.approvedByArchitect ?? false,
      approvedBy: project.approvedBy || null,
      signOffTimestamp: project.architectSignOffAt || null,
      overrideJustification: project.architectJustifiedOverride || null,
    },
    scores: {
      cleanCoreScore: project.cleanCoreScore ?? null,
      complexityScore: project.complexityScore ?? null,
      criticalityScore: project.criticalityScore ?? null,
    },
  };
}

/**
 * Human-readable Architecture Decision Record (Markdown) — the "why RAP not CAP,
 * why object X transformed and Y deferred" artifact, bound to the run's evidence.
 * Reuses the same decision data as generateDecisionRecord, formatted as a standard ADR.
 */
export function generateArchitectureDecisionRecord(project: Project): string {
  const arch = project.targetArchitecture ? (ARCH_LABELS[project.targetArchitecture] || project.targetArchitecture) : 'Not determined';
  const original = project.originalRecommendation ? (ARCH_LABELS[project.originalRecommendation] || project.originalRecommendation) : '—';
  const overridden = !!project.targetArchitecture && !!project.originalRecommendation && project.targetArchitecture !== project.originalRecommendation;
  const confidence = project.recommendationConfidence != null ? `${project.recommendationConfidence}%` : '—';
  const signDate = project.architectSignOffAt ? new Date(project.architectSignOffAt as string).toISOString().slice(0, 10) : '';
  const status = project.approvedByArchitect
    ? `Accepted — self-attested by ${mdCell(project.approvedBy || 'architect')}${signDate ? ' on ' + signDate : ''}`
    : 'Proposed — pending architect sign-off';
  const fp = project.auditMetadata?.inputFingerprint;
  const mc = project.auditMetadata?.modelCard;
  const worklist: WorklistItem[] = project.worklist || [];
  const lvlOf = (w: WorklistItem) => w.level || (w.status === 'signed_off' ? 'fully' : w.status === 'in_review' ? 'review' : 'open');
  const fully = worklist.filter((w) => lvlOf(w) === 'fully');
  const review = worklist.filter((w) => lvlOf(w) === 'review');
  const oos = worklist.filter((w) => w.level === 'out_of_scope');
  const list = (items: WorklistItem[]) =>
    items.length
      ? items.map((w) => `- **${mdCell(w.title)}** (${w.severity || w.effort || '—'}) — ${mdCell(w.recommendation)}${w.location ? ` — at ${mdCell(w.location)}` : ''}`).join('\n')
      : '_None._';

  return `# Architecture Decision Record — ${mdCell(project.name)}

> Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}.
> A machine-assisted decision record for review — it does not replace a formal, governed architecture sign-off.

| Field | Value |
|---|---|
| Status | ${mdCell(status)} |
| Decision | ${mdCell(arch)} |
| Engine recommendation | ${mdCell(original)}${overridden ? ' (overridden by architect)' : ''} |
| Confidence | ${confidence} |
| Clean Core / Complexity / Criticality | ${project.cleanCoreScore ?? '—'} / ${project.complexityScore ?? '—'} / ${project.criticalityScore ?? '—'} |

## Context

${fp ? `Analysis of "${mdCell(fp.fileName || 'uploaded ABAP')}" (${mdCell(fp.objectType || 'object')}, ${fp.lineCount ?? '—'} LOC). ` : ''}The deterministic evidence engine classified the custom code against SAP Clean Core extensibility guidelines and routed it to a target track before any AI narrative was generated.

## Decision

Adopt **${mdCell(arch)}** as the target architecture.${overridden ? ` This overrides the engine's recommendation (${mdCell(original)}). Architect's reasoning: ${mdCell(project.architectJustifiedOverride || '—')}.` : ''}

## Rationale

${mdCell(project.recommendationJustification || 'Derived from the deterministic evidence — data coupling, released-API usage and transaction semantics.')} (Confidence: ${confidence}.)

## Considered options

- **In-App ABAP Cloud (RAP)** — extend within the S/4HANA boundary on released APIs.
- **Side-by-Side on SAP BTP (CAP)** — decoupled Node.js/TypeScript services, upgrade-safe.
- **Integration Suite / Event Mesh / Retire** — for middleware, asynchronous, or deprecation cases.

## Scope & consequences

**Transformed / fully mapped — ${fully.length}**
${list(fully)}

**Needs expert review — ${review.length}**
${list(review)}

**Out of scope / deferred — ${oos.length}**
${list(oos)}

## Evidence

- Extensibility route: ${mdCell(project.extensibilityRoute || arch)}
- Engine: ${mdCell(mc?.engineVersion || APP_VERSION)} · SAP catalog: ${mdCell((mc as any)?.catalogVersion || '2024.FPS02')}
- Bound to the immutable, HMAC-signed analysis run — the findings behind this decision are reproducible.

## Limitations

- Generated content is a draft for architect review — not a production-ready deliverable or a certified SAP acceptance.
- The sign-off is self-attested (from the signed-in user's session), not a formally governed organizational approval.
- Dynamic ABAP, Dynpro / screen flows and kernel calls are flagged, not auto-resolved.

*Generated by Clean-Core.io ${APP_VERSION}.*
`;
}

export function generateFindingsCsv(project: Project): string {
  const entries = project.dataCoupling || [];
  if (entries.length === 0) return 'Table Name,Access Type,Is Custom,Risk Level,Recommendation\n(No data coupling entries detected)\n';

  const header = 'Table Name,Access Type,Is Custom,Risk Level,Recommendation';
  const rows = entries.map(e =>
    [e.tableName, e.accessType, e.isCustom ? 'Yes' : 'No', e.riskLevel, e.recommendation]
      .map(csvCell)
      .join(',')
  );
  return [header, ...rows].join('\n') + '\n';
}

export function generateModelCard(project: Project): string {
  const mc = project.auditMetadata?.modelCard;
  return `# Model Card — AI Component Documentation

> This document identifies the AI components involved in the analysis and transformation.

## Model Information

| Field | Value |
|---|---|
| Model Provider | ${mc?.provider || 'google-gemini'} |
| Model Identifier | ${mc?.model || '—'} |
| Platform Version | ${mc?.engineVersion || APP_VERSION} |
| SAP API Catalog | ${(mc as any)?.catalogVersion || '2024.FPS02'} |
| BYOK (Bring Your Own Key) | ${mc?.byokUsed ? 'Yes — user-provided API key' : 'No — platform key'} |

## Processing Timestamps

| Stage | Timestamp |
|---|---|
| Analysis | ${mc?.analysisTimestamp || '—'} |
| Design | ${mc?.designTimestamp || '—'} |
| Transformation | ${mc?.transformationTimestamp || '—'} |

## Usage Context

The AI model was used for:
- Structural analysis of legacy ABAP code
- Clean Core compliance scoring
- Extensibility route recommendation
- Code transformation to RAP/CAP target architecture
- Test case generation

The AI output is a draft for human review. All architecture decisions require explicit architect sign-off before adoption.
`;
}

export function generateKnownLimitations(): string {
  return `# Known Limitations

> This document lists known limitations of the automated analysis and transformation engine.

## Static Analysis Constraints

- **Dynamic ABAP calls** (e.g., \`CALL FUNCTION func_name\` with variable names) cannot be fully resolved statically.
- **Dynpro / Screen Flows** are not 1:1 cloud-capable. UI5/Fiori migration requires separate design work.
- **Batch Input scenarios** require manual process redesign — they cannot be automatically converted.
- **Unreleased APIs** detected during mapping must not be used in production without SAP confirmation.

## Data Access Constraints

- **Direct table write operations** (INSERT, UPDATE, DELETE on standard tables) require explicit architecture approval.
- **Custom table dependencies** need manual classification (operational data vs. configuration vs. master data).
- **Cross-system RFC/IDoc dependencies** are flagged but not automatically migrated.

## Code Quality Constraints

- **Generated code is a draft** — it is not a production-approved deliverable.
- **Business semantics** may be misinterpreted without domain expert review.
- **Test coverage** is estimated, not measured. ABAP-Unit / Node.js tests must be executed in a real sandbox.
- **Performance characteristics** (e.g., mass data processing, parallel execution) are not validated.

## Compliance Constraints

- This analysis does not constitute a formal security audit.
- Data protection classification (personal data, financial data) requires a dedicated DPO review.
- Tenant connections are restricted to sandbox systems — production access is not supported.

---

*Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}*
`;
}

/**
 * F-04: Provenance manifest. The HMAC signature proves the *integrity* of the
 * generated package (these exact bytes were produced server-side and not altered
 * afterwards) — it does NOT by itself prove every value was deterministically
 * computed by the server. This file labels each evidence file and headline field
 * by provenance class, so an auditor can separate deterministic facts from
 * model-generated drafts and self-attested inputs.
 */
export function generateProvenanceManifest(project: Project): string {
  const mc = project.auditMetadata?.modelCard;
  const approved = project.approvedByArchitect ? 'yes (self-attested)' : 'no';
  return `# Provenance & Evidence Classes

> Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}.

The HMAC signature in \`manifest.json\` protects the **integrity** of this package —
that these exact bytes were generated server-side and have not been altered since.
It does **not**, on its own, attest that every value was deterministically computed
by the server. Use the classes below to separate deterministic facts from
model-generated drafts and user-attested inputs.

**Provenance classes**

- \`server-computed\` — deterministic engine output: parser findings, SHA-256 hashes, catalog lookup, scores.
- \`model-generated\` — AI (Google Gemini) narrative / justification; a draft for review, not a fact.
- \`user-attested\` — supplied or confirmed in the signed-in user's own session (self-attested), not independently verified.
- \`static\` — fixed disclaimer / limitations text.

**Per-file provenance**

| Evidence file | Provenance class(es) |
|---|---|
| 00-executive-summary.md / .doc | server-computed (scores, fingerprint) · user-attested (project name, sign-off) |
| 01-input-fingerprint.json | server-computed |
| 02-decision-record.json | server-computed (scores) · model-generated (justification) · user-attested (architect review) |
| 03-findings.csv | server-computed |
| 04-model-card.md | server-computed |
| 05-known-limitations.md | static |
| 06-architecture-decision-record.md | server-computed (evidence) · model-generated (rationale) · user-attested (decision, sign-off) |
| manifest.json | server-computed (file hashes, manifest hash, HMAC signature) |

**Headline field provenance**

| Field | Class |
|---|---|
| Clean Core / Complexity / Criticality scores | server-computed |
| Input SHA-256 fingerprint, lines of code | server-computed |
| Data-coupling findings | server-computed |
| Target-architecture route (RAP/CAP/…) | server-computed (deterministic router) |
| Recommendation justification / narrative | model-generated (${mdCell(mc?.model || 'Gemini')}) |
| Architect sign-off / approver / override reason | user-attested (approved: ${approved}) |
| HMAC signature | server-computed integrity seal over the manifest hash |

This is a decision-support package, not a certification. Model-generated and
user-attested content must be validated by a qualified reviewer.
`;
}

/**
 * Generates a Compliance Audit Pack as a ZIP blob.
 *
 * v2.0: Delegates entirely to the server-authoritative /api/audit-pack/create,
 * which generates the evidence files, hashes them, and HMAC-signs the manifest
 * server-side. The client only downloads the resulting ZIP.
 *
 * @param project  Hydrated project (includes active run data)
 * @param idToken  Firebase ID token for authenticating the sign request
 */
export async function generateAuditPack(project: Project, idToken: string): Promise<Blob> {
  // v1.20 §5 — Server-authoritative audit-pack generation.
  // The pack (evidence files + signed manifest) is generated and signed entirely
  // server-side from the immutable run, so the signature attests to server content,
  // not to client-supplied file hashes. The client only downloads the result.
  const projectId = (project as any).id || '';
  const runId = project.activeRunId;
  if (!runId) {
    throw new Error('Cannot generate Audit Pack without an active analysis run. Please re-run the analysis first.');
  }

  const res = await fetch('/api/audit-pack/create', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${idToken}`,
    },
    body: JSON.stringify({ projectId }),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => 'Unknown error');
    throw new Error(`Audit pack generation failed (${res.status}): ${errText}`);
  }

  return await res.blob();
}
