/**
 * Compliance Audit Pack Generator (v1.17.0)
 *
 * Generates an exportable ZIP containing structured evidence for
 * architecture governance reviews, compliance audits, and enterprise
 * decision documentation.
 *
 * v1.17: Adds manifest.json with SHA-256 file hashes and HMAC-SHA256
 * cryptographic signature via server-side /api/export/sign endpoint.
 *
 * Security: This module never includes secrets, credentials, API keys,
 * or unmasked tenant URLs in the export. Only hashes, timestamps,
 * model identifiers, and architecture decisions are included.
 */

import JSZip from 'jszip';
import type { Project } from '@/lib/types';
import { APP_VERSION, APP_RELEASE_DATE } from '@/lib/version';

/** Compute SHA-256 hash of a string using the Web Crypto API (browser-compatible). */
async function sha256(content: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(content);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

interface ManifestFile {
  path: string;
  sha256: string;
  bytes: number;
}

export interface AuditPackManifest {
  version: string;
  runId: string;
  projectId: string;
  generatedAt: string;
  engineVersion: string;
  sapApiCatalogVersion: string;
  files: ManifestFile[];
  manifestHash: string;
  signed: boolean;
  signature: string;
  signatureError?: string;
  runHash?: string;
}

const ARCH_LABELS: Record<string, string> = {
  rap: 'In-App ABAP Cloud (RAP)',
  cap: 'Side-by-Side BTP (CAP)',
  integration: 'SAP Integration Suite',
  event: 'SAP Event Mesh',
  retire: 'Retire / Decommission',
};

function generateExecutiveSummary(project: Project): string {
  const fp = project.auditMetadata?.inputFingerprint;
  const mc = project.auditMetadata?.modelCard;
  const arch = project.targetArchitecture ? ARCH_LABELS[project.targetArchitecture] || project.targetArchitecture : 'Not determined';
  const approved = project.approvedByArchitect ? '✓ Approved' : '○ Pending';
  const approver = project.approvedBy ? ` by ${project.approvedBy}` : '';
  const signOffDate = project.architectSignOffAt
    ? new Date(project.architectSignOffAt as string).toISOString()
    : '—';

  return `# Compliance Audit Pack — Executive Summary

> Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}
> This document is a machine-generated draft for review. It does not replace a formal architecture sign-off.

---

## Project Overview

| Field | Value |
|---|---|
| Project Name | ${project.name} |
| Analysis Status | ${project.status || 'unknown'} |
| Clean Core Score | ${project.cleanCoreScore ?? '—'}/100 |
| Complexity Score | ${project.complexityScore ?? '—'}/100 |
| Criticality Score | ${project.criticalityScore ?? '—'}/100 |
| Target Architecture | ${arch} |
| Architect Approval | ${approved}${approver} |
| Sign-Off Date | ${signOffDate} |
| Extensibility Route | ${project.extensibilityRoute || '—'} |

## Input Summary

| Field | Value |
|---|---|
| File Name | ${fp?.fileName || '—'} |
| Object Type | ${fp?.objectType || '—'} |
| Lines of Code | ${fp?.lineCount ?? '—'} |
| Input Size | ${fp?.byteSize ? `${(fp.byteSize / 1024).toFixed(1)} KB` : '—'} |
| SHA-256 Fingerprint | \`${fp?.sha256 || '—'}\` |
| Upload Timestamp | ${fp?.uploadedAt || '—'} |

## Engine Metadata

| Field | Value |
|---|---|
| Platform Version | ${mc?.engineVersion || APP_VERSION} |
| SAP API Catalog | ${(mc as any)?.catalogVersion || '2024.FPS02'} |
| Model Provider | ${mc?.provider || 'google-gemini'} |
| Model | ${mc?.model || '—'} |
| BYOK Used | ${mc?.byokUsed ? 'Yes' : 'No'} |
| Analysis Timestamp | ${mc?.analysisTimestamp || '—'} |
| Design Timestamp | ${mc?.designTimestamp || '—'} |
| Transformation Timestamp | ${mc?.transformationTimestamp || '—'} |

---

## Audit Pack Disclaimer

This audit pack documents an automated modernization analysis. The results represent a technical and architectural decision aid. They do not replace a formal architecture sign-off, a data protection review, or a production SAP acceptance test.

Generated code is a draft for review — not a production-ready deliverable.
`;
}

function generateExecutiveSummaryDoc(project: Project): string {
  const fp = project.auditMetadata?.inputFingerprint;
  const mc = project.auditMetadata?.modelCard;
  const arch = project.targetArchitecture ? ARCH_LABELS[project.targetArchitecture] || project.targetArchitecture : 'Not determined';
  const approved = project.approvedByArchitect ? '✓ Approved' : '○ Pending';
  const approver = project.approvedBy ? ` by ${project.approvedBy}` : '';
  const signOffDate = project.architectSignOffAt
    ? new Date(project.architectSignOffAt as string).toISOString()
    : '—';
  const score = project.cleanCoreScore ?? '—';
  const complexity = project.complexityScore ?? '—';
  const criticality = project.criticalityScore ?? '—';

  return `<html xmlns:o='urn:schemas-microsoft-com:office:office' 
      xmlns:w='urn:schemas-microsoft-com:office:word' 
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <title>Compliance Audit Pack — Executive Summary</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 11pt; line-height: 1.5; color: #333333; margin: 1in; }
    h1 { font-family: 'Calibri Light', sans-serif; font-size: 24pt; color: #006b2c; border-bottom: 2px solid #006b2c; padding-bottom: 5px; margin-top: 0; }
    h2 { font-family: 'Calibri Light', sans-serif; font-size: 16pt; color: #00873a; margin-top: 20px; border-bottom: 1px solid #D3D3D3; padding-bottom: 3px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 20px; }
    th { background-color: #006b2c; color: #ffffff; text-align: left; font-weight: bold; padding: 6px 10px; border: 1px solid #D3D3D3; }
    td { padding: 6px 10px; border: 1px solid #D3D3D3; vertical-align: top; }
    tr:nth-child(even) td { background-color: #F0Fdf4; }
    blockquote { border-left: 4px solid #00873a; padding-left: 10px; margin-left: 0; color: #595959; font-style: italic; }
    code { font-family: 'Consolas', monospace; background-color: #F2F2F2; padding: 2px 4px; font-size: 10pt; }
    .footer { font-size: 9pt; color: #7F7F7F; text-align: right; margin-top: 40px; border-top: 1px solid #D3D3D3; padding-top: 5px; }
  </style>
</head>
<body>
  <h1>Compliance Audit Pack — Executive Summary</h1>
  <blockquote>
    Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}<br/>
    This document is a machine-generated draft for review. It does not replace a formal architecture sign-off.
  </blockquote>

  <h2>Project Overview</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Project Name</td><td>${project.name}</td></tr>
      <tr><td>Analysis Status</td><td>${project.status || 'unknown'}</td></tr>
      <tr><td>Clean Core Score</td><td>${score}/100</td></tr>
      <tr><td>Complexity Score</td><td>${complexity}/100</td></tr>
      <tr><td>Criticality Score</td><td>${criticality}/100</td></tr>
      <tr><td>Target Architecture</td><td>${arch}</td></tr>
      <tr><td>Architect Approval</td><td>${approved}${approver}</td></tr>
      <tr><td>Sign-Off Date</td><td>${signOffDate}</td></tr>
      <tr><td>Extensibility Route</td><td>${project.extensibilityRoute || '—'}</td></tr>
    </tbody>
  </table>

  <h2>Input Summary</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>File Name</td><td>${fp?.fileName || '—'}</td></tr>
      <tr><td>Object Type</td><td>${fp?.objectType || '—'}</td></tr>
      <tr><td>Lines of Code</td><td>${fp?.lineCount ?? '—'}</td></tr>
      <tr><td>Input Size</td><td>${fp?.byteSize ? `${(fp.byteSize / 1024).toFixed(1)} KB` : '—'}</td></tr>
      <tr><td>SHA-256 Fingerprint</td><td><code>${fp?.sha256 || '—'}</code></td></tr>
      <tr><td>Upload Timestamp</td><td>${fp?.uploadedAt || '—'}</td></tr>
    </tbody>
  </table>

  <h2>Engine Metadata</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Platform Version</td><td>${mc?.engineVersion || APP_VERSION}</td></tr>
      <tr><td>Model Provider</td><td>${mc?.provider || 'google-gemini'}</td></tr>
      <tr><td>Model</td><td>${mc?.model || '—'}</td></tr>
      <tr><td>BYOK Used</td><td>${mc?.byokUsed ? 'Yes' : 'No'}</td></tr>
      <tr><td>Analysis Timestamp</td><td>${mc?.analysisTimestamp || '—'}</td></tr>
      <tr><td>Design Timestamp</td><td>${mc?.designTimestamp || '—'}</td></tr>
      <tr><td>Transformation Timestamp</td><td>${mc?.transformationTimestamp || '—'}</td></tr>
    </tbody>
  </table>

  <h2>Audit Pack Disclaimer</h2>
  <p>This audit pack documents an automated modernization analysis. The results represent a technical and architectural decision aid. They do not replace a formal architecture sign-off, a data protection review, or a production SAP acceptance test.</p>
  <p>Generated code is a draft for review — not a production-ready deliverable.</p>

  <div class="footer">
    Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}
  </div>
</body>
</html>`;
}

function generateDecisionRecord(project: Project): object {
  return {
    projectName: project.name,
    generatedAt: new Date().toISOString(),
    engineVersion: APP_VERSION,
    recommendation: {
      targetArchitecture: project.targetArchitecture || null,
      originalRecommendation: project.originalRecommendation || null,
      confidence: project.recommendationConfidence ?? null,
      justification: project.recommendationJustification || null,
    },
    architectReview: {
      approved: project.approvedByArchitect ?? false,
      approvedBy: project.approvedBy || null,
      signOffTimestamp: project.architectSignOffAt || null,
      overrideJustification: project.architectJustifiedOverride || null,
    },
    scores: {
      cleanCoreScore: project.cleanCoreScore ?? null,
      complexityScore: project.complexityScore ?? null,
      criticalityScore: project.criticalityScore ?? null,
    },
  };
}

function generateFindingsCsv(project: Project): string {
  const entries = project.dataCoupling || [];
  if (entries.length === 0) return 'Table Name,Access Type,Is Custom,Risk Level,Recommendation\n(No data coupling entries detected)\n';

  const header = 'Table Name,Access Type,Is Custom,Risk Level,Recommendation';
  const rows = entries.map(e =>
    `"${e.tableName}","${e.accessType}","${e.isCustom ? 'Yes' : 'No'}","${e.riskLevel}","${e.recommendation.replace(/"/g, '""')}"`
  );
  return [header, ...rows].join('\n') + '\n';
}

function generateModelCard(project: Project): string {
  const mc = project.auditMetadata?.modelCard;
  return `# Model Card — AI Component Documentation

> This document identifies the AI components involved in the analysis and transformation.

## Model Information

| Field | Value |
|---|---|
| Model Provider | ${mc?.provider || 'google-gemini'} |
| Model Identifier | ${mc?.model || '—'} |
| Platform Version | ${mc?.engineVersion || APP_VERSION} |
| SAP API Catalog | ${(mc as any)?.catalogVersion || '2024.FPS02'} |
| BYOK (Bring Your Own Key) | ${mc?.byokUsed ? 'Yes — user-provided API key' : 'No — platform key'} |

## Processing Timestamps

| Stage | Timestamp |
|---|---|
| Analysis | ${mc?.analysisTimestamp || '—'} |
| Design | ${mc?.designTimestamp || '—'} |
| Transformation | ${mc?.transformationTimestamp || '—'} |

## Usage Context

The AI model was used for:
- Structural analysis of legacy ABAP code
- Clean Core compliance scoring
- Extensibility route recommendation
- Code transformation to RAP/CAP target architecture
- Test case generation

The AI output is a draft for human review. All architecture decisions require explicit architect sign-off before adoption.
`;
}

function generateKnownLimitations(): string {
  return `# Known Limitations

> This document lists known limitations of the automated analysis and transformation engine.

## Static Analysis Constraints

- **Dynamic ABAP calls** (e.g., \`CALL FUNCTION func_name\` with variable names) cannot be fully resolved statically.
- **Dynpro / Screen Flows** are not 1:1 cloud-capable. UI5/Fiori migration requires separate design work.
- **Batch Input scenarios** require manual process redesign — they cannot be automatically converted.
- **Unreleased APIs** detected during mapping must not be used in production without SAP confirmation.

## Data Access Constraints

- **Direct table write operations** (INSERT, UPDATE, DELETE on standard tables) require explicit architecture approval.
- **Custom table dependencies** need manual classification (operational data vs. configuration vs. master data).
- **Cross-system RFC/IDoc dependencies** are flagged but not automatically migrated.

## Code Quality Constraints

- **Generated code is a draft** — it is not a production-approved deliverable.
- **Business semantics** may be misinterpreted without domain expert review.
- **Test coverage** is estimated, not measured. ABAP-Unit / Node.js tests must be executed in a real sandbox.
- **Performance characteristics** (e.g., mass data processing, parallel execution) are not validated.

## Compliance Constraints

- This analysis does not constitute a formal security audit.
- Data protection classification (personal data, financial data) requires a dedicated DPO review.
- Tenant connections are restricted to sandbox systems — production access is not supported.

---

*Generated by Clean-Core.io ${APP_VERSION} on ${new Date().toISOString()}*
`;
}

/**
 * Generates a Compliance Audit Pack as a ZIP blob.
 *
 * v1.17: Includes a signed manifest.json with SHA-256 hashes of all
 * files. The HMAC signature is obtained from the server-side
 * /api/export/sign endpoint to keep the signing key secret.
 *
 * @param project  Hydrated project (includes active run data)
 * @param idToken  Firebase ID token for authenticating the sign request
 */
export async function generateAuditPack(project: Project, idToken: string): Promise<Blob> {
  const zip = new JSZip();

  // 1. Generate all audit pack files in memory
  const fileContents: Record<string, string> = {
    '00-executive-summary.md': generateExecutiveSummary(project),
    '00-executive-summary.doc': generateExecutiveSummaryDoc(project),
    '01-input-fingerprint.json': JSON.stringify(
      project.auditMetadata?.inputFingerprint || { note: 'No fingerprint available — analysis may predate v1.10.0' },
      null, 2
    ),
    '02-decision-record.json': JSON.stringify(
      generateDecisionRecord(project),
      null, 2
    ),
    '03-findings.csv': generateFindingsCsv(project),
    '04-model-card.md': generateModelCard(project),
    '05-known-limitations.md': generateKnownLimitations(),
  };

  // 2. Compute SHA-256 hashes of each file using Web Crypto API
  const manifestFiles: ManifestFile[] = [];
  for (const [path, content] of Object.entries(fileContents)) {
    const hash = await sha256(content);
    const bytes = new TextEncoder().encode(content).byteLength;
    manifestFiles.push({ path, sha256: hash, bytes });
    zip.file(path, content);
  }

  // 3. Request cryptographic signature from server
  let manifest: AuditPackManifest;
  const generatedAt = new Date().toISOString();
  const projectId = (project as any).id || '';
  const runId = project.activeRunId || '';

  try {
    const signResponse = await fetch('/api/export/sign', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${idToken}`,
      },
      body: JSON.stringify({ projectId, runId, files: manifestFiles }),
    });

    if (!signResponse.ok) {
      const errText = await signResponse.text().catch(() => 'Unknown error');
      throw new Error(`Sign API returned ${signResponse.status}: ${errText}`);
    }

    const signData = await signResponse.json();

    manifest = {
      version: '2.0',
      runId,
      projectId,
      generatedAt: signData.generatedAt || generatedAt,
      engineVersion: APP_VERSION,
      sapApiCatalogVersion: (project.auditMetadata?.modelCard as any)?.catalogVersion || '2024.FPS02',
      files: manifestFiles,
      manifestHash: signData.manifestHash,
      signed: true,
      signature: signData.signature,
      runHash: (project as any).runHash || '',
    };
  } catch (err: any) {
    // Graceful fallback: generate unsigned manifest
    console.warn('Audit Pack signing failed, generating unsigned manifest:', err.message);

    // Compute local manifest hash for integrity (even without server signature)
    const sortedFiles = [...manifestFiles].sort((a, b) => a.path.localeCompare(b.path));
    const runHash = (project as any).runHash || '';
    const engineVersion = (project.auditMetadata?.modelCard as any)?.engineVersion || APP_VERSION;
    const sapApiCatalogVersion = (project.auditMetadata?.modelCard as any)?.catalogVersion || '2024.FPS02';
    const canonicalSuffix = `${projectId}:${runId}:${runHash}:${engineVersion}:${sapApiCatalogVersion};`;
    const canonicalManifest = sortedFiles.map(f => `${f.path}:${f.sha256}`).join(';') + ';' + canonicalSuffix;
    const localManifestHash = await sha256(canonicalManifest);

    manifest = {
      version: '2.0',
      runId,
      projectId,
      generatedAt,
      engineVersion: APP_VERSION,
      sapApiCatalogVersion: (project.auditMetadata?.modelCard as any)?.catalogVersion || '2024.FPS02',
      files: manifestFiles,
      manifestHash: localManifestHash,
      signed: false,
      signature: '',
      signatureError: err.message || 'Signing service unavailable',
      runHash,
    };
  }

  // 4. Add manifest.json as the last file (it does NOT list itself)
  zip.file('manifest.json', JSON.stringify(manifest, null, 2));

  if (typeof window === 'undefined') {
    const buf = await zip.generateAsync({ type: 'nodebuffer' });
    return buf as any;
  }

  return zip.generateAsync({ type: 'blob' });
}
