/**
 * What Clean-Core.io actually does, stated concretely enough to be judged.
 *
 * Each capability carries what it produces, what it saves, what it costs in effort
 * and quota, and where it stops. That last field is the important one: the
 * governing principle of the project is "belegt, nicht behauptet" — proven, not
 * claimed — and a capability list without limits is a claim.
 */

export interface Capability {
  stage: string;
  title: string;
  /** What the reader gets, in concrete artefacts. */
  output: string;
  benefit: string;
  effort: string;
  /** What it does NOT do. Stated as plainly as the benefit. */
  limit: string;
}

export const CAPABILITIES: Capability[] = [
  {
    stage: 'Stage 1',
    title: 'Evidence-based analysis',
    output:
      'A Clean Core score, an A–D readiness estimate, a list of findings with line numbers, the database coupling, a code inventory, and complexity and criticality scores — sealed as a signed, immutable Run.',
    benefit:
      'Replaces "we think this object is risky" with a per-object finding somebody can check. A deterministic engine parses the source before any AI is involved, so the evidence does not depend on a model\'s mood.',
    effort:
      'One click, about two minutes. Costs one of your five transformations. Re-analysing the same source is free.',
    limit:
      'The A–D grade is an experimental preview estimate, not an authoritative ATC classification. Confirm with SAP ADT and ATC for your target release.',
  },
  {
    stage: 'Stage 2',
    title: 'Extensibility routing',
    output:
      'A recommended route — in-app ABAP Cloud (RAP) or side-by-side BTP (CAP) — with a confidence score and the reasoning that produced it.',
    benefit:
      'The RAP-or-CAP argument, resolved per object with stated criteria instead of preference. The reasoning is inspectable, so it survives a review rather than only a demo.',
    effort: 'Included in the analysis. No extra step, no extra unit.',
    limit:
      'It is a recommendation from static evidence. It does not know your organisation\'s platform strategy, licensing, or team skills — all of which legitimately override it.',
  },
  {
    stage: 'Stage 3',
    title: 'Solution design',
    output:
      'A target architecture mapped onto the recommended route, released SAP APIs proposed in place of direct table access, and the non-functional requirements spelled out.',
    benefit:
      'Turns "use released APIs" into named APIs from the SAP Business Accelerator Hub for the tables your code actually touches.',
    effort: 'Two to three minutes. Included — no further unit is charged.',
    limit:
      'API mapping is grounded in SAP\'s published catalogue. Where no released successor exists, it says so rather than inventing one.',
  },
  {
    stage: 'Stage 4',
    title: 'Code transformation',
    output:
      'A RAP or CAP implementation generated from the legacy source, shown side by side with the original, scroll-synchronised.',
    benefit:
      'The first compliant draft, in minutes rather than days — and reviewable statement by statement instead of as a black box.',
    effort: 'Three minutes. Included.',
    limit:
      'A draft for an architect to review, not a deployment artefact. It is generated by a third-party AI model and provided as-is. Nothing here removes the need for an expert to read it.',
  },
  {
    stage: 'Stage 5',
    title: 'Test generation and execution',
    output: 'ABAP Unit test classes against the transformed logic, executed in an isolated sandbox with per-case results.',
    benefit:
      'Modernised code arrives with tests attached, so the review has something to run rather than only something to read.',
    effort: 'Two minutes. Included.',
    limit:
      'Tests are generated from the code, so they encode its behaviour — including any bug it already had. They verify the transformation, not the original business requirement.',
  },
  {
    stage: 'Stage 6',
    title: 'Documentation',
    output:
      'BPMN 2.0 process diagrams for import into SAP Signavio or SAP Build, plus business-facing procedures and control points, exportable to Confluence.',
    benefit:
      'The documentation that normally never gets written, produced as a by-product of the analysis rather than as a separate project.',
    effort: 'Two minutes. Included.',
    limit: 'Generated from the code. It describes what the object does, not why the business wanted it.',
  },
  {
    stage: 'Stage 7',
    title: 'Delivery and audit evidence',
    output:
      'An abapGit-compatible ZIP with sources and tests, plus a signed audit evidence pack recording exactly what was analysed, by which engine and catalogue version, and what it concluded.',
    benefit:
      'The package goes into your own Eclipse ADT environment for compilation and verification — and the signature makes the analysis tamper-evident, which is what lets a recommendation hold up in a governance review.',
    effort: 'One minute. Included.',
    limit:
      'The signature proves the analysis was not altered after the fact. It does not certify that the conclusion is correct — that is what your architect is for.',
  },
];

/** Deliberate boundaries. Stated up front, not buried in a disclaimer. */
export const HONEST_SCOPE: { claim: string; reality: string }[] = [
  {
    claim: 'Is this a code translator?',
    reality:
      'No. It is an evidence-first accelerator. The generated code matters less than the evidence and the reasoning that led to it.',
  },
  {
    claim: 'Does it replace architecture governance?',
    reality:
      'No. It does not replace enterprise-architecture approval, SAP release checks, privacy review, penetration testing, or production migration governance.',
  },
  {
    claim: 'Can I deploy the output to production?',
    reality:
      'Not directly. Every artefact is a draft for expert evaluation. Review, test and approve it with a qualified SAP architect first.',
  },
  {
    claim: 'What happens to my source code?',
    reality:
      'It is processed by the Google Gemini API for the AI stages and is not used to train Google\'s models under those terms. Your data is stored in the EU (europe-west1, Belgium). Bring your own Gemini key and it is used exclusively through a server-side proxy, encrypted at rest with AES-256-GCM, never exposed to the browser.',
  },
  {
    claim: 'What does it cost?',
    reality:
      'Nothing. Five transformations per account, no locked features, no paid tier. Your own Gemini key removes the limit entirely.',
  },
];
