import { createHash } from 'crypto';
import { getLevelRuleVersion } from '@/lib/abap/catalog-service';
import { readSource, revealedRules } from '@/lib/first-look';
import { APP_VERSION } from '@/lib/version';
import { buildDemoWorkspace, type DemoWorkspaceData } from '@/lib/demo-workspace';
import { TOUR_STATIONS, type TourPlace } from '@/lib/demo-tour';

/**
 * Which engine and which rule version the demo was last regenerated for —
 * roadmap 3.0.7, `DESIGN.md` §6.1.2: *„ändert sich Engine oder Regelversion,
 * wird die Demo mit dem Release neu erzeugt"*.
 *
 * **How the demo is produced today.** It is not stored. `lib/demo-project.ts`
 * and `lib/demo-workspace.ts` run the engine of the deployed release over
 * `public/starter-examples/Z_MM_PO_APPROVAL.abap` on the server, so what a reader sees
 * cannot drift from the engine that serves it. What *can* drift is everything
 * written about it: the tour's stations need a rule to reveal, a construct the
 * engine did not judge, a process with levels, a successor with evidence; the
 * roadmap, the mockups and the landing page quote its figures. None of that
 * moves when the engine does, and nobody is told.
 *
 * **So the regeneration is a record, and the guard compares it.**
 * `npm run demo:regenerate` (`scripts/regenerate-demo.ts`) measures the demo
 * and writes `lib/demo-release.json`: the source digest, the A–D rule version,
 * the catalog version, a digest of the whole engine output and the headline
 * figures. `tests/demo-release-guard.spec.ts` measures again and goes red when
 * the two disagree — so a release that changes the engine or the rule version
 * cannot ship without the demo being regenerated in the same change, and the
 * diff of the JSON is where a reviewer sees what the demo now says. It also
 * goes red when a tour station has lost its target.
 *
 * The app version is written down but not compared: a release that bumps the
 * version and leaves the engine alone produces the same demo, and a guard that
 * fires anyway teaches people to regenerate without looking.
 */

export interface DemoReleaseFigures {
  findings: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  info: number;
  cleanCoreScore: number;
  recommendedRoute: string;
  notDeterminedConstructs: number;
  rulesRevealed: number;
  processSteps: number;
  processLevels: number;
  standardCandidates: number;
  itFindingRows: number;
  inventoryObjects: number;
  tables: number;
  handoverMissing: number;
}

export interface DemoRelease {
  source: { file: string; sha256: string };
  /** `getLevelRuleVersion().version` — the rule fingerprint and both SAP artifacts. */
  ruleVersion: string;
  catalogVersion: string;
  /** SHA-256 over everything the demo workspace is built from — findings, route, map, IT rows. */
  engineOutput: string;
  figures: DemoReleaseFigures;
}

/** What the file holds: the measurement plus when and with what it was taken. */
export interface DemoReleaseRecord extends DemoRelease {
  $comment: string;
  /** Informational only — see the module comment. */
  regeneratedWith: string;
}

export const DEMO_RELEASE_FILE = 'lib/demo-release.json';

export const DEMO_RELEASE_COMMENT =
  'Generated by `npm run demo:regenerate` - do not edit. tests/demo-release-guard.spec.ts fails when the engine or the rule version no longer produces this demo.';

const sha256 = (text: string) => createHash('sha256').update(text).digest('hex');

export function figuresOf(data: DemoWorkspaceData): DemoReleaseFigures {
  const { demo } = data;
  const s = demo.analyze.summary;
  return {
    findings: demo.analyze.findings.length,
    critical: s.criticalCount,
    high: s.highCount,
    medium: s.mediumCount,
    low: s.lowCount,
    info: s.infoCount,
    cleanCoreScore: demo.analyze.cleanCoreScore,
    recommendedRoute: demo.design.recommendedRoute,
    notDeterminedConstructs: demo.analyze.coverage.unassessed.length,
    rulesRevealed: revealedRules(readSource(data.source).ruleSet).length,
    processSteps: data.processMap.elements.length,
    processLevels: data.processMap.planes.length,
    standardCandidates: demo.transformation.plan.filter((p) => p.successor).length,
    itFindingRows: data.itFindings.rows.length,
    inventoryObjects: demo.documentation.inventory.length,
    tables: demo.documentation.coupling.length,
    handoverMissing: demo.delivery.missing.length,
  };
}

/** The demo as the engine of this checkout produces it. */
export function measureDemoRelease(data: DemoWorkspaceData = buildDemoWorkspace()): DemoRelease {
  return {
    source: { file: data.demo.sourceFile, sha256: sha256(data.source) },
    ruleVersion: getLevelRuleVersion().version,
    catalogVersion: data.demo.catalogVersion,
    // `\r` removed before hashing: `buildDemoProject` reads the file as the
    // checkout wrote it, and a CRLF working copy on Windows would otherwise
    // record a different engine output than the LF image in CI for the same
    // engine (measured: identical once the carriage returns are gone).
    engineOutput: sha256(
      JSON.stringify({ demo: data.demo, processMap: data.processMap, it: data.itFindings }).replace(/\\r/g, ''),
    ),
    figures: figuresOf(data),
  };
}

export function recordOf(release: DemoRelease): DemoReleaseRecord {
  return { $comment: DEMO_RELEASE_COMMENT, regeneratedWith: APP_VERSION, ...release };
}

/**
 * Every way the record and the measurement disagree, one line each, in words a
 * reviewer can act on. Empty when the demo is current.
 */
export function demoReleaseDrift(recorded: DemoRelease, measured: DemoRelease): string[] {
  const out: string[] = [];
  if (recorded.source?.sha256 !== measured.source.sha256) out.push('the example source changed');
  if (recorded.ruleVersion !== measured.ruleVersion) {
    out.push(`rule version: recorded "${recorded.ruleVersion}", now "${measured.ruleVersion}"`);
  }
  if (recorded.catalogVersion !== measured.catalogVersion) {
    out.push(`catalog version: recorded "${recorded.catalogVersion}", now "${measured.catalogVersion}"`);
  }
  const keys = Object.keys(measured.figures) as (keyof DemoReleaseFigures)[];
  for (const key of keys) {
    const was = recorded.figures?.[key];
    const now = measured.figures[key];
    if (was !== now) out.push(`${key}: recorded ${JSON.stringify(was)}, now ${JSON.stringify(now)}`);
  }
  if (recorded.engineOutput !== measured.engineOutput && out.length === 0) {
    out.push('the engine output changed (same headline figures, different findings, lines, map or IT rows)');
  }
  return out;
}

/**
 * What each tour station needs to find at its place, as a figure that must be
 * above zero — or `null` for a place that is honest when empty (Management's
 * answer and the cost simulation *say* what is missing, and that is the lesson).
 */
export const TOUR_TARGETS: Record<TourPlace, { figure: keyof DemoReleaseFigures; min: number } | null> = {
  reveal: { figure: 'rulesRevealed', min: 1 },
  'not-determined': { figure: 'notDeterminedConstructs', min: 1 },
  'process-map': { figure: 'processSteps', min: 1 },
  'process-levels': { figure: 'processLevels', min: 2 },
  'confirm-rule': { figure: 'rulesRevealed', min: 1 },
  'standard-fit': { figure: 'standardCandidates', min: 1 },
  'it-chain': { figure: 'itFindingRows', min: 1 },
  management: null,
  'four-buckets': { figure: 'findings', min: 1 },
  costs: null,
  decision: null,
  handover: { figure: 'handoverMissing', min: 1 },
};

/** The stations whose place would be empty in this demo — a tour that points at nothing is a claim. */
export function stationsWithoutTarget(figures: DemoReleaseFigures): string[] {
  return TOUR_STATIONS.filter((station) => {
    const target = TOUR_TARGETS[station.place];
    if (!target) return false;
    const value = figures[target.figure];
    return typeof value !== 'number' || value < target.min;
  }).map((station) => `${station.place} needs ${TOUR_TARGETS[station.place]?.figure} >= ${TOUR_TARGETS[station.place]?.min}`);
}
